/*
 * N5g-ddnmf_Discovery API
 *
 * N5g-ddnmf_Discovery Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package N5g-ddnmf_Discovery

import (
	"time"
)

// AnnounceUpdateData - Represents Announce Authorize Data to update
type AnnounceUpdateData struct {

	DiscType DiscoveryType `json:"discType"`

	// string with format 'date-time' as defined in OpenAPI.
	ValidityTime time.Time `json:"validityTime"`

	// Contains the ProSe Application Code.
	ProseAppCode string `json:"proseAppCode,omitempty"`
}
