/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_Nudm_SDM

type DataSetNameAnyOf string

// List of DataSetNameAnyOf
const (
	AM DataSetNameAnyOf = "AM"
	SMF_SEL DataSetNameAnyOf = "SMF_SEL"
	UEC_SMF DataSetNameAnyOf = "UEC_SMF"
	UEC_SMSF DataSetNameAnyOf = "UEC_SMSF"
	SMS_SUB DataSetNameAnyOf = "SMS_SUB"
	SM DataSetNameAnyOf = "SM"
	TRACE DataSetNameAnyOf = "TRACE"
	SMS_MNG DataSetNameAnyOf = "SMS_MNG"
	LCS_PRIVACY DataSetNameAnyOf = "LCS_PRIVACY"
	LCS_MO DataSetNameAnyOf = "LCS_MO"
	UEC_AMF DataSetNameAnyOf = "UEC_AMF"
	V2_X DataSetNameAnyOf = "V2X"
	LCS_BCA DataSetNameAnyOf = "LCS_BCA"
	PROSE DataSetNameAnyOf = "PROSE"
	UC DataSetNameAnyOf = "UC"
	MBS DataSetNameAnyOf = "MBS"
)
