/*
 * Nmfaf_3caDataManagement
 *
 * MFAF 3GPP Consumer Adaptor (3CA) Data Management Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package Nmfaf_3caDataManagement

// PfdData - List of Application IDs and/or AF IDs managed by a given NEF Instance
type PfdData struct {

	AppIds []string `json:"appIds,omitempty"`

	AfIds []string `json:"afIds,omitempty"`
}
