/*
 * Unified Data Repository Service API file for Application Data
 *
 * The API version is defined in 3GPP TS 29.504   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: -
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package Application_Data

type EventAnyOf string

// List of EventAnyOf
const (
	SUCCESS_UE_POL_DEL_SP EventAnyOf = "SUCCESS_UE_POL_DEL_SP"
	UNSUCCESS_UE_POL_DEL_SP EventAnyOf = "UNSUCCESS_UE_POL_DEL_SP"
)
