/*
 * Eees Application Context Relocation Service
 *
 * Eees Application Context Relocation Service.   © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_Eees_AppContextRelocation

// AcrInitReq - Represents the parameters to request ACR with action initiation.
type AcrInitReq struct {

	RequestorId string `json:"requestorId"`

	// String identifying a Gpsi shall contain either an External Id or an MSISDN.  It shall be formatted as follows -External Identifier= \"extid-'extid', where 'extid'  shall be formatted according to clause 19.7.2 of 3GPP TS 23.003 that describes an  External Identifier.  
	UeId string `json:"ueId,omitempty"`

	AcId string `json:"acId,omitempty"`

	EasId string `json:"easId,omitempty"`

	TEasEndpoint EndPoint `json:"tEasEndpoint"`

	SEasEndpoint EndPoint `json:"sEasEndpoint,omitempty"`

	PrevTEasEndpoint EndPoint `json:"prevTEasEndpoint,omitempty"`

	RouteReq *RouteToLocation `json:"routeReq,omitempty"`

	EasNotifInd bool `json:"easNotifInd"`

	PrevEasNotifInd bool `json:"prevEasNotifInd,omitempty"`

	EecCtxtReloc EecCtxtReloc `json:"eecCtxtReloc,omitempty"`
}
