/*
 * NR NRM
 *
 * OAS 3.0.1 specification of the NR NRM © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 17.7.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package NrNrm
// CollectionPeriodM6NrType : See details in 3GPP TS 32.422 clause 5.10.34.
type CollectionPeriodM6NrType string

// List of CollectionPeriodM6NrType
const (
	_120MS CollectionPeriodM6NrType = "120ms"
	_240MS CollectionPeriodM6NrType = "240ms"
	_480MS CollectionPeriodM6NrType = "480ms"
	_640MS CollectionPeriodM6NrType = "640ms"
	_1024MS CollectionPeriodM6NrType = "1024ms"
	_2048MS CollectionPeriodM6NrType = "2048ms"
	_5120MS CollectionPeriodM6NrType = "5120ms"
	_10240MS CollectionPeriodM6NrType = "10240ms"
	_20480MS CollectionPeriodM6NrType = "20480ms"
	_40960MS CollectionPeriodM6NrType = "40960ms"
	_1MIN CollectionPeriodM6NrType = "1min"
	_6MIN CollectionPeriodM6NrType = "6min"
	_12MIN CollectionPeriodM6NrType = "12min"
	_30MIN CollectionPeriodM6NrType = "30min"
)
