/*
 * Nudm_UEAU
 *
 * UDM UE Authentication Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_Nudm_UEAU

type GbaAuthTypeAnyOf string

// List of GbaAuthTypeAnyOf
const (
	DIGEST_AKAV1_MD5 GbaAuthTypeAnyOf = "DIGEST_AKAV1_MD5"
)
