/*
 * M1_ContentHostingProvisioning
 *
 * 5GMS AF M1 Content Hosting Provisioning API © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package M1_ContentHostingProvisioning

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// CreateContentHostingConfiguration - Create (and optionally upload) the Content Hosting Configuration for the specified Provisioning Session
func CreateContentHostingConfiguration(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// DestroyContentHostingConfiguration - Destroy the current Content Hosting Configuration of the specified Provisioning Session
func DestroyContentHostingConfiguration(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PatchContentHostingConfiguration - Patch the Content Hosting Configuration for the specified Provisioning Session
func PatchContentHostingConfiguration(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PurgeContentHostingCache - Purge the content of the cache for the Content Hosting Configuration of the specified Provisioning Session
func PurgeContentHostingCache(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// RetrieveContentHostingConfiguration - Retrieve the Content Hosting Configuration of the specified Provisioning Session
func RetrieveContentHostingConfiguration(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UpdateContentHostingConfiguration - Update the Content Hosting Configuration for the specified Provisioning Session
func UpdateContentHostingConfiguration(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
