/*
 * M1_ContentHostingProvisioning
 *
 * 5GMS AF M1 Content Hosting Provisioning API © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package M1_ContentHostingProvisioning

// DistributionConfiguration - A content distribution configuration.
type DistributionConfiguration struct {

	// String chosen by the 5GMS AF to serve as an identifier in a resource URI.
	ContentPreparationTemplateId string `json:"contentPreparationTemplateId,omitempty"`

	CanonicalDomainName string `json:"canonicalDomainName"`

	DomainNameAlias string `json:"domainNameAlias"`

	PathRewriteRules []PathRewriteRule `json:"pathRewriteRules,omitempty"`

	CachingConfigurations []CachingConfiguration `json:"cachingConfigurations,omitempty"`

	GeoFencing DistributionConfigurationGeoFencing `json:"geoFencing,omitempty"`

	UrlSignature DistributionConfigurationUrlSignature `json:"urlSignature,omitempty"`

	// String chosen by the 5GMS AF to serve as an identifier in a resource URI.
	CertificateId string `json:"certificateId,omitempty"`

	SupplementaryDistributionNetworks DistributionConfigurationSupplementaryDistributionNetworks `json:"supplementaryDistributionNetworks,omitempty"`
}
