/*
 * 3gpp-analyticsexposure
 *
 * API for Analytics Exposure.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.1.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_AnalyticsExposure

// AbnormalExposure - Represents a user's abnormal behavior information.
type AbnormalExposure struct {

	Gpsis []string `json:"gpsis,omitempty"`

	// String providing an application identifier.
	AppId string `json:"appId,omitempty"`

	Excep Exception `json:"excep"`

	// Unsigned integer indicating Sampling Ratio (see clauses 4.15.1 of 3GPP TS 23.502), expressed in percent.  
	Ratio int32 `json:"ratio,omitempty"`

	// Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
	Confidence int32 `json:"confidence,omitempty"`

	AddtMeasInfo AdditionalMeasurement `json:"addtMeasInfo,omitempty"`
}
