/*
 * Npcf_PolicyAuthorization Service API
 *
 * PCF Policy Authorization Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package Npcf_PolicyAuthorization

type RequestedQosMonitoringParameterAnyOf string

// List of RequestedQosMonitoringParameterAnyOf
const (
	DOWNLINK RequestedQosMonitoringParameterAnyOf = "DOWNLINK"
	UPLINK RequestedQosMonitoringParameterAnyOf = "UPLINK"
	ROUND_TRIP RequestedQosMonitoringParameterAnyOf = "ROUND_TRIP"
)
