/*
 * Npcf_PolicyAuthorization Service API
 *
 * PCF Policy Authorization Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package Npcf_PolicyAuthorization

type DnaiChangeTypeAnyOf string

// List of DnaiChangeTypeAnyOf
const (
	EARLY DnaiChangeTypeAnyOf = "EARLY"
	EARLY_LATE DnaiChangeTypeAnyOf = "EARLY_LATE"
	LATE DnaiChangeTypeAnyOf = "LATE"
)
