/*
 * Npcf_PolicyAuthorization Service API
 *
 * PCF Policy Authorization Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package Npcf_PolicyAuthorization

// PcfAddressingInfo - Contains PCF address information.
type PcfAddressingInfo struct {

	// Fully Qualified Domain Name
	PcfFqdn string `json:"pcfFqdn,omitempty"`

	// IP end points of the PCF hosting the Npcf_PolicyAuthorization service.
	PcfIpEndPoints []IpEndPoint `json:"pcfIpEndPoints,omitempty"`

	// contains the binding indications of the PCF.
	BindingInfo string `json:"bindingInfo,omitempty"`
}
