/*
 * Nhss_EE
 *
 * HSS Event Exposure.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package Nhss_EE

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// DeleteEeSubscription - Unsubscribe
func DeleteEeSubscription(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
