/*
 * EES Session with QoS API
 *
 * API for EES Session with Qos service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_Eees_SessionWithQoS

// SponsorInformation - Represents a sponsor information.
type SponsorInformation struct {

	// It indicates Sponsor ID.
	SponsorId string `json:"sponsorId"`

	// It indicates Application Service Provider ID.
	AspId string `json:"aspId"`
}
