/*
 * 3gpp-monitoring-event
 *
 * API for Monitoring Event.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package MonitoringEvent

type LocationFailureCauseAnyOf string

// List of LocationFailureCauseAnyOf
const (
	POSITIONING_DENIED LocationFailureCauseAnyOf = "POSITIONING_DENIED"
	UNSUPPORTED_BY_UE LocationFailureCauseAnyOf = "UNSUPPORTED_BY_UE"
	NOT_REGISTED_UE LocationFailureCauseAnyOf = "NOT_REGISTED_UE"
	UNSPECIFIED LocationFailureCauseAnyOf = "UNSPECIFIED"
)
