/*
 * 3gpp-monitoring-event
 *
 * API for Monitoring Event.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package MonitoringEvent

type AssociationTypeAnyOf string

// List of AssociationTypeAnyOf
const (
	IMEI AssociationTypeAnyOf = "IMEI"
	IMEISV AssociationTypeAnyOf = "IMEISV"
)
