/*
 * 3gpp-monitoring-event
 *
 * API for Monitoring Event.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package MonitoringEvent

type UcPurposeAnyOf string

// List of UcPurposeAnyOf
const (
	ANALYTICS UcPurposeAnyOf = "ANALYTICS"
	MODEL_TRAINING UcPurposeAnyOf = "MODEL_TRAINING"
	NW_CAP_EXPOSURE UcPurposeAnyOf = "NW_CAP_EXPOSURE"
	EDGEAPP_UE_LOCATION UcPurposeAnyOf = "EDGEAPP_UE_LOCATION"
)
