/*
 * Ndccf_ContextManagement
 *
 * DCCF Context Management Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_Ndccf_ContextManagement

import (
	"time"
)

// AdditionalMeasurement - Represents additional measurement information.
type AdditionalMeasurement struct {

	UnexpLoc NetworkAreaInfo `json:"unexpLoc,omitempty"`

	UnexpFlowTeps []IpEthFlowDescription `json:"unexpFlowTeps,omitempty"`

	UnexpWakes []time.Time `json:"unexpWakes,omitempty"`

	DdosAttack AddressList `json:"ddosAttack,omitempty"`

	WrgDest AddressList `json:"wrgDest,omitempty"`

	Circums []CircumstanceDescription `json:"circums,omitempty"`
}
