/*
 * Ndccf_ContextManagement
 *
 * DCCF Context Management Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_Ndccf_ContextManagement

type N1MessageClassAnyOf string

// List of N1MessageClassAnyOf
const (
	_5_GMM N1MessageClassAnyOf = "5GMM"
	SM N1MessageClassAnyOf = "SM"
	LPP N1MessageClassAnyOf = "LPP"
	SMS N1MessageClassAnyOf = "SMS"
	UPDP N1MessageClassAnyOf = "UPDP"
	LCS N1MessageClassAnyOf = "LCS"
)
