/*
 * EES Application Client Information_API
 *
 * API for EES Application Client Information.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_Eees_AppClientInformation

// ServiceArea - Represents a service area information of the EdgeApp entity.
type ServiceArea struct {

	TopServAr TopologicalServiceArea `json:"topServAr,omitempty"`

	GeoServAr GeographicalServiceArea `json:"geoServAr,omitempty"`
}
