/*
 * Nchf_ConvergedCharging
 *
 * ConvergedCharging Service    © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 3.1.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_Nchf_ConvergedCharging

type RoleOfUeAnyOf string

// List of RoleOfUeAnyOf
const (
	ANNOUNCING_UE RoleOfUeAnyOf = "ANNOUNCING_UE"
	MONITORING_UE RoleOfUeAnyOf = "MONITORING_UE"
	REQUESTOR_UE RoleOfUeAnyOf = "REQUESTOR_UE"
	REQUESTED_UE RoleOfUeAnyOf = "REQUESTED_UE"
)
