/*
 * Nchf_ConvergedCharging
 *
 * ConvergedCharging Service    © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 3.1.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_Nchf_ConvergedCharging

type SupplementaryServiceModeAnyOf string

// List of SupplementaryServiceModeAnyOf
const (
	CFU SupplementaryServiceModeAnyOf = "CFU"
	CFB SupplementaryServiceModeAnyOf = "CFB"
	CFNR SupplementaryServiceModeAnyOf = "CFNR"
	CFNL SupplementaryServiceModeAnyOf = "CFNL"
	CD SupplementaryServiceModeAnyOf = "CD"
	CFNRC SupplementaryServiceModeAnyOf = "CFNRC"
	ICB SupplementaryServiceModeAnyOf = "ICB"
	OCB SupplementaryServiceModeAnyOf = "OCB"
	ACR SupplementaryServiceModeAnyOf = "ACR"
	BLIND_TRANFER SupplementaryServiceModeAnyOf = "BLIND_TRANFER"
	CONSULTATIVE_TRANFER SupplementaryServiceModeAnyOf = "CONSULTATIVE_TRANFER"
)
