/*
 * Nchf_ConvergedCharging
 *
 * ConvergedCharging Service    © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 3.1.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_Nchf_ConvergedCharging

import (
	"time"
)

type ImsChargingInformation struct {

	EventType SipEventType `json:"eventType,omitempty"`

	IMSNodeFunctionality ImsNodeFunctionality `json:"iMSNodeFunctionality,omitempty"`

	RoleOfNode RoleOfImsNode `json:"roleOfNode,omitempty"`

	UserInformation UserInformation `json:"userInformation,omitempty"`

	UserLocationInfo UserLocation `json:"userLocationInfo,omitempty"`

	// String with format \"time-numoffset\" optionally appended by \"daylightSavingTime\", where  - \"time-numoffset\" shall represent the time zone adjusted for daylight saving time and be    encoded as time-numoffset as defined in clause 5.6 of IETF RFC 3339;  - \"daylightSavingTime\" shall represent the adjustment that has been made and shall be    encoded as \"+1\" or \"+2\" for a +1 or +2 hours adjustment.   The example is for 8 hours behind UTC, +1 hour adjustment for Daylight Saving Time. 
	UeTimeZone string `json:"ueTimeZone,omitempty"`

	Var3gppPSDataOffStatus Model3GpppsDataOffStatus `json:"3gppPSDataOffStatus,omitempty"`

	IsupCause IsupCause `json:"isupCause,omitempty"`

	ControlPlaneAddress ImsAddress `json:"controlPlaneAddress,omitempty"`

	VlrNumber string `json:"vlrNumber,omitempty"`

	MscAddress string `json:"mscAddress,omitempty"`

	UserSessionID string `json:"userSessionID,omitempty"`

	OutgoingSessionID string `json:"outgoingSessionID,omitempty"`

	SessionPriority ImsSessionPriority `json:"sessionPriority,omitempty"`

	CallingPartyAddresses []string `json:"callingPartyAddresses,omitempty"`

	CalledPartyAddress string `json:"calledPartyAddress,omitempty"`

	NumberPortabilityRoutinginformation string `json:"numberPortabilityRoutinginformation,omitempty"`

	CarrierSelectRoutingInformation string `json:"carrierSelectRoutingInformation,omitempty"`

	AlternateChargedPartyAddress string `json:"alternateChargedPartyAddress,omitempty"`

	RequestedPartyAddress []string `json:"requestedPartyAddress,omitempty"`

	CalledAssertedIdentities []string `json:"calledAssertedIdentities,omitempty"`

	CalledIdentityChanges []CalledIdentityChange `json:"calledIdentityChanges,omitempty"`

	AssociatedURI []string `json:"associatedURI,omitempty"`

	// string with format 'date-time' as defined in OpenAPI.
	TimeStamps time.Time `json:"timeStamps,omitempty"`

	ApplicationServerInformation []string `json:"applicationServerInformation,omitempty"`

	InterOperatorIdentifier []InterOperatorIdentifier `json:"interOperatorIdentifier,omitempty"`

	ImsChargingIdentifier string `json:"imsChargingIdentifier,omitempty"`

	RelatedICID string `json:"relatedICID,omitempty"`

	RelatedICIDGenerationNode string `json:"relatedICIDGenerationNode,omitempty"`

	TransitIOIList []string `json:"transitIOIList,omitempty"`

	EarlyMediaDescription []EarlyMediaDescription `json:"earlyMediaDescription,omitempty"`

	SdpSessionDescription []string `json:"sdpSessionDescription,omitempty"`

	SdpMediaComponent []SdpMediaComponent `json:"sdpMediaComponent,omitempty"`

	ServedPartyIPAddress ImsAddress `json:"servedPartyIPAddress,omitempty"`

	ServerCapabilities ServerCapabilities `json:"serverCapabilities,omitempty"`

	TrunkGroupID TrunkGroupId `json:"trunkGroupID,omitempty"`

	BearerService string `json:"bearerService,omitempty"`

	ImsServiceId string `json:"imsServiceId,omitempty"`

	MessageBodies []MessageBody `json:"messageBodies,omitempty"`

	AccessNetworkInformation []string `json:"accessNetworkInformation,omitempty"`

	AdditionalAccessNetworkInformation string `json:"additionalAccessNetworkInformation,omitempty"`

	CellularNetworkInformation string `json:"cellularNetworkInformation,omitempty"`

	AccessTransferInformation []AccessTransferInformation `json:"accessTransferInformation,omitempty"`

	AccessNetworkInfoChange []AccessNetworkInfoChange `json:"accessNetworkInfoChange,omitempty"`

	ImsCommunicationServiceID string `json:"imsCommunicationServiceID,omitempty"`

	ImsApplicationReferenceID string `json:"imsApplicationReferenceID,omitempty"`

	// Integer where the allowed values correspond to the value range of an unsigned 32-bit integer. 
	CauseCode int32 `json:"causeCode,omitempty"`

	ReasonHeader []string `json:"reasonHeader,omitempty"`

	InitialIMSChargingIdentifier string `json:"initialIMSChargingIdentifier,omitempty"`

	NniInformation []NniInformation `json:"nniInformation,omitempty"`

	FromAddress string `json:"fromAddress,omitempty"`

	ImsEmergencyIndication bool `json:"imsEmergencyIndication,omitempty"`

	ImsVisitedNetworkIdentifier string `json:"imsVisitedNetworkIdentifier,omitempty"`

	SipRouteHeaderReceived string `json:"sipRouteHeaderReceived,omitempty"`

	SipRouteHeaderTransmitted string `json:"sipRouteHeaderTransmitted,omitempty"`

	TadIdentifier TadIdentifier `json:"tadIdentifier,omitempty"`

	FeIdentifierList string `json:"feIdentifierList,omitempty"`
}
