/*
 * Nchf_ConvergedCharging
 *
 * ConvergedCharging Service    © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 3.1.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_Nchf_ConvergedCharging

type ServiceProfileChargingInformation struct {

	ServiceProfileIdentifier string `json:"serviceProfileIdentifier,omitempty"`

	SNSSAIList []Snssai `json:"sNSSAIList,omitempty"`

	Latency int32 `json:"latency,omitempty"`

	Availability float32 `json:"availability,omitempty"`

	Jitter int32 `json:"jitter,omitempty"`

	Reliability string `json:"reliability,omitempty"`

	MaxNumberofUEs int32 `json:"maxNumberofUEs,omitempty"`

	CoverageArea string `json:"coverageArea,omitempty"`

	DLThptPerSlice Throughput `json:"dLThptPerSlice,omitempty"`

	DLThptPerUE Throughput `json:"dLThptPerUE,omitempty"`

	ULThptPerSlice Throughput `json:"uLThptPerSlice,omitempty"`

	ULThptPerUE Throughput `json:"uLThptPerUE,omitempty"`

	MaxNumberofPDUsessions int32 `json:"maxNumberofPDUsessions,omitempty"`

	KPIMonitoringList string `json:"kPIMonitoringList,omitempty"`

	SupportedAccessTechnology int32 `json:"supportedAccessTechnology,omitempty"`

	AddServiceProfileInfo string `json:"addServiceProfileInfo,omitempty"`
}
