/*
 * Nchf_ConvergedCharging
 *
 * ConvergedCharging Service    © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 3.1.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_Nchf_ConvergedCharging

type ClassIdentifierAnyOf string

// List of ClassIdentifierAnyOf
const (
	PERSONAL ClassIdentifierAnyOf = "PERSONAL"
	ADVERTISEMENT ClassIdentifierAnyOf = "ADVERTISEMENT"
	INFORMATIONAL ClassIdentifierAnyOf = "INFORMATIONAL"
	AUTO ClassIdentifierAnyOf = "AUTO"
)
