/*
 * Nchf_ConvergedCharging
 *
 * ConvergedCharging Service    © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 3.1.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_Nchf_ConvergedCharging

type ReauthorizationDetails struct {

	// Integer where the allowed values correspond to the value range of an unsigned 32-bit integer. 
	ServiceId int32 `json:"serviceId,omitempty"`

	// Integer where the allowed values correspond to the value range of an unsigned 32-bit integer. 
	RatingGroup int32 `json:"ratingGroup,omitempty"`

	QuotaManagementIndicator QuotaManagementIndicator `json:"quotaManagementIndicator,omitempty"`
}
