/*
 * Neasdf_DNSContext
 *
 * EASDF DNS Context Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_Neasdf_DNSContext

type ApplyActionAnyOf string

// List of ApplyActionAnyOf
const (
	BUFFER ApplyActionAnyOf = "BUFFER"
	REPORT ApplyActionAnyOf = "REPORT"
	FORWARD ApplyActionAnyOf = "FORWARD"
	DISCARD ApplyActionAnyOf = "DISCARD"
)
