/*
 * Ngmlc_Location
 *
 * GMLC Location Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.1.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_Ngmlc_Location

import (
	"time"
)

// LocationData - Contains the response parameters in ProvideLocation service operation
type LocationData struct {

	// String identifying a Gpsi shall contain either an External Id or an MSISDN.  It shall be formatted as follows -External Identifier= \"extid-'extid', where 'extid'  shall be formatted according to clause 19.7.2 of 3GPP TS 23.003 that describes an  External Identifier.  
	Gpsi string `json:"gpsi,omitempty"`

	// String identifying a Supi that shall contain either an IMSI, a network specific identifier, a Global Cable Identifier (GCI) or a Global Line Identifier (GLI) as specified in clause  2.2A of 3GPP TS 23.003. It shall be formatted as follows  - for an IMSI \"imsi-<imsi>\", where <imsi> shall be formatted according to clause 2.2    of 3GPP TS 23.003 that describes an IMSI.  - for a network specific identifier \"nai-<nai>, where <nai> shall be formatted    according to clause 28.7.2 of 3GPP TS 23.003 that describes an NAI.  - for a GCI \"gci-<gci>\", where <gci> shall be formatted according to clause 28.15.2    of 3GPP TS 23.003.  - for a GLI \"gli-<gli>\", where <gli> shall be formatted according to clause 28.16.2 of    3GPP TS 23.003.To enable that the value is used as part of an URI, the string shall    only contain characters allowed according to the \"lower-with-hyphen\" naming convention    defined in 3GPP TS 29.501. 
	Supi string `json:"supi,omitempty"`

	LocationEstimate GeographicArea `json:"locationEstimate,omitempty"`

	CivicAddress CivicAddress `json:"civicAddress,omitempty"`

	LocalLocationEstimate LocalArea `json:"localLocationEstimate,omitempty"`

	// Indicates value of the age of the location estimate.
	AgeOfLocationEstimate int32 `json:"ageOfLocationEstimate,omitempty"`

	// string with format 'date-time' as defined in OpenAPI.
	TimestampOfLocationEstimate time.Time `json:"timestampOfLocationEstimate,omitempty"`

	PositioningDataList []PositioningMethodAndUsage `json:"positioningDataList,omitempty"`

	GnssPositioningDataList []GnssPositioningMethodAndUsage `json:"gnssPositioningDataList,omitempty"`

	AccuracyFulfilmentIndicator AccuracyFulfilmentIndicator `json:"accuracyFulfilmentIndicator,omitempty"`

	UeVelocity VelocityEstimate `json:"ueVelocity,omitempty"`

	// LDR Reference.
	LdrReference string `json:"ldrReference,omitempty"`

	// Indicates value of altitude.
	Altitude float64 `json:"altitude,omitempty"`

	// LMF identification.
	ServingLMFIdentification string `json:"servingLMFIdentification,omitempty"`

	LocationPrivacyVerResult LocationPrivacyVerResult `json:"locationPrivacyVerResult,omitempty"`

	SuccessType SuccessType `json:"successType,omitempty"`

	AchievedQos MinorLocationQoS `json:"achievedQos,omitempty"`
}
