/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package Nnrf_NFManagement

// SnssaiEasdfInfoItem - Set of parameters supported by EASDF for a given S-NSSAI
type SnssaiEasdfInfoItem struct {

	SNssai ExtSnssai `json:"sNssai"`

	DnnEasdfInfoList []DnnEasdfInfoItem `json:"dnnEasdfInfoList"`
}
