/*
 * 3gpp-am-policyauthorization
 *
 * API for AM policy authorization.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package AMPolicyAuthorization

// AppAmContextExpUpdateData - Contains the modification(s) to be applied to the Individual application AM context exposure resource. 
type AppAmContextExpUpdateData struct {

	EvSubscs *AmEventsSubscDataRm `json:"evSubscs,omitempty"`

	HighThruInd bool `json:"highThruInd,omitempty"`

	CovReqs []GeographicalArea `json:"covReqs,omitempty"`

	// Unsigned integer identifying a period of time in units of seconds.
	PolicyDuration int32 `json:"policyDuration,omitempty"`
}
