/*
 * MSGG_L3GDelivery
 *
 * API for MSGG L3G Message Delivery Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package MSGG_L3GDelivery

// ReportDeliveryStatus - Possible values are: - REPT_DELY_SUCCESS: Indicates that the report delivery is successful. - REPT_DELY_FAILED: Indicates that the report delivery is failed. 
type ReportDeliveryStatus struct {
}
