/*
 * N32 Handshake API
 *
 * N32-c Handshake Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_N32_Handshake

// N32fErrorInfo - N32-f error information
type N32fErrorInfo struct {

	N32fMessageId string `json:"n32fMessageId"`

	N32fErrorType N32fErrorType `json:"n32fErrorType"`

	N32fContextId string `json:"n32fContextId,omitempty"`

	FailedModificationList []FailedModificationInfo `json:"failedModificationList,omitempty"`

	ErrorDetailsList []N32fErrorDetail `json:"errorDetailsList,omitempty"`
}
