/*
 * Eees_EASDiscovery
 *
 * API for EAS Discovery. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_Eees_EASDiscovery

// EasDiscoveryNotification - Notification of EAS discovery information.
type EasDiscoveryNotification struct {

	// Identifier of the individual service provisioning subscription for which the service provisioning notification is delivered.
	SubId string `json:"subId"`

	EventType EasDiscEventIds `json:"eventType"`

	// List of EAS discovery information.
	DiscoveredEas []DiscoveredEas `json:"discoveredEas"`
}
