/*
 * CAPIF_Routing_Info_API
 *
 * API for Routing information.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_CAPIF_Routing_Info_API

// Protocol - Possible values are: - HTTP_1_1: HTTP version 1.1 - HTTP_2: HTTP version 2 
type Protocol struct {
}
