/*
 * CAPIF_Routing_Info_API
 *
 * API for Routing information.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_CAPIF_Routing_Info_API

// AefLocation - The location information (e.g. civic address, GPS coordinates, data center ID) where the AEF providing the service API is located. 
type AefLocation struct {

	CivicAddr CivicAddress `json:"civicAddr,omitempty"`

	GeoArea GeographicArea `json:"geoArea,omitempty"`

	// Identifies the data center where the AEF providing the service API is located. 
	DcId string `json:"dcId,omitempty"`
}
