/*
 * Nucmf_Provisioning
 *
 * UCMF_Provisioning Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_Nucmf_Provisioning

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// GetProvisioning - Get an Individual UE radio capability provisioning
func GetProvisioning(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// RemoveProvisioning - Remove an Individual UE radio capability provisioning
func RemoveProvisioning(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// ReplaceProvisioning - Replace (PUT) an Individual UE radio capability provisioning
func ReplaceProvisioning(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UpdateProvisioning - Update (PATCH) an Individual UE radio capability provisioning
func UpdateProvisioning(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
