/*
 * 3GPP 5GC NRM
 *
 * OAS 3.0.1 specification of the 5GC NRM © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 17.7.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package 5GcNrm

type TrafficControlData struct {

	TcId string `json:"tcId,omitempty"`

	FlowStatus FlowStatus `json:"flowStatus,omitempty"`

	RedirectInfo RedirectInformation `json:"redirectInfo,omitempty"`

	AddRedirectInfo []RedirectInformation `json:"addRedirectInfo,omitempty"`

	MuteNotif bool `json:"muteNotif,omitempty"`

	TrafficSteeringPolIdDl *string `json:"trafficSteeringPolIdDl,omitempty"`

	TrafficSteeringPolIdUl *string `json:"trafficSteeringPolIdUl,omitempty"`

	RouteToLocs []RouteToLocation `json:"routeToLocs,omitempty"`

	TraffCorreInd bool `json:"traffCorreInd,omitempty"`

	UpPathChgEvent *UpPathChgEvent `json:"upPathChgEvent,omitempty"`

	SteerFun SteeringFunctionality `json:"steerFun,omitempty"`

	SteerModeDl SteeringMode `json:"steerModeDl,omitempty"`

	SteerModeUl SteeringMode `json:"steerModeUl,omitempty"`

	MulAccCtrl MulticastAccessControl `json:"mulAccCtrl,omitempty"`

	SnssaiList []Snssai `json:"snssaiList,omitempty"`
}
