/*
 * 3GPP 5GC NRM
 *
 * OAS 3.0.1 specification of the 5GC NRM © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 17.7.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package 5GcNrm

type PccRule struct {

	// Univocally identifies the PCC rule within a PDU session.
	PccRuleId string `json:"pccRuleId,omitempty"`

	FlowInfoList []FlowInformation `json:"flowInfoList,omitempty"`

	ApplicationId string `json:"applicationId,omitempty"`

	// string with format 'bytes' as defined in OpenAPI
	AppDescriptor string `json:"appDescriptor,omitempty"`

	// Represents the content version of some content.
	ContentVersion int32 `json:"contentVersion,omitempty"`

	// Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
	Precedence int32 `json:"precedence,omitempty"`

	AfSigProtocol AfSigProtocol `json:"afSigProtocol,omitempty"`

	IsAppRelocatable bool `json:"isAppRelocatable,omitempty"`

	IsUeAddrPreserved bool `json:"isUeAddrPreserved,omitempty"`

	QosData [][]QosData `json:"qosData,omitempty"`

	AltQosParams [][]QosData `json:"altQosParams,omitempty"`

	TrafficControlData [][]TrafficControlData `json:"trafficControlData,omitempty"`

	ConditionData *ConditionData `json:"conditionData,omitempty"`

	TscaiInputDl *TscaiInputContainer `json:"tscaiInputDl,omitempty"`

	TscaiInputUl *TscaiInputContainer `json:"tscaiInputUl,omitempty"`
}
