/*
 * 3GPP 5GC NRM
 *
 * OAS 3.0.1 specification of the 5GC NRM © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 17.7.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package 5GcNrm

type ManagedElementAttr struct {

	DnPrefix string `json:"dnPrefix,omitempty"`

	ManagedElementTypeList []string `json:"managedElementTypeList,omitempty"`

	UserLabel string `json:"userLabel,omitempty"`

	LocationName string `json:"locationName,omitempty"`

	ManagedBy []string `json:"managedBy,omitempty"`

	VendorName string `json:"vendorName,omitempty"`

	UserDefinedState string `json:"userDefinedState,omitempty"`

	SwVersion string `json:"swVersion,omitempty"`

	PriorityLabel int32 `json:"priorityLabel,omitempty"`

	SupportedPerfMetricGroups []SupportedPerfMetricGroup `json:"supportedPerfMetricGroups,omitempty"`

	SupportedTraceMetrics []string `json:"supportedTraceMetrics,omitempty"`
}
