/*
 * 3GPP 5GC NRM
 *
 * OAS 3.0.1 specification of the 5GC NRM © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 17.7.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package 5GcNrm
// CommModelType : any of enumrated value
type CommModelType string

// List of CommModelType
const (
	DIRECT_COMMUNICATION_WO_NRF CommModelType = "DIRECT_COMMUNICATION_WO_NRF"
	DIRECT_COMMUNICATION_WITH_NRF CommModelType = "DIRECT_COMMUNICATION_WITH_NRF"
	INDIRECT_COMMUNICATION_WO_DEDICATED_DISCOVERY CommModelType = "INDIRECT_COMMUNICATION_WO_DEDICATED_DISCOVERY"
	INDIRECT_COMMUNICATION_WITH_DEDICATED_DISCOVERY CommModelType = "INDIRECT_COMMUNICATION_WITH_DEDICATED_DISCOVERY"
)
