/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_Nudr_DR

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// CreateNIDDAuthorizationInfo - Create NIDD Authorization Info
func CreateNIDDAuthorizationInfo(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetNiddAuthorizationInfo - Retrieve NIDD Authorization Info
func GetNiddAuthorizationInfo(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// ModifyNiddAuthorizationInfo - Modify NIDD Authorization Info
func ModifyNiddAuthorizationInfo(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// RemoveNiddAuthorizationInfo - Delete NIDD Authorization Info
func RemoveNiddAuthorizationInfo(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
