/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_Nudr_DR

type PrivacyCheckRelatedActionAnyOf string

// List of PrivacyCheckRelatedActionAnyOf
const (
	NOT_ALLOWED PrivacyCheckRelatedActionAnyOf = "LOCATION_NOT_ALLOWED"
	ALLOWED_WITH_NOTIFICATION PrivacyCheckRelatedActionAnyOf = "LOCATION_ALLOWED_WITH_NOTIFICATION"
	ALLOWED_WITHOUT_NOTIFICATION PrivacyCheckRelatedActionAnyOf = "LOCATION_ALLOWED_WITHOUT_NOTIFICATION"
	ALLOWED_WITHOUT_RESPONSE PrivacyCheckRelatedActionAnyOf = "LOCATION_ALLOWED_WITHOUT_RESPONSE"
	RESTRICTED_WITHOUT_RESPONSE PrivacyCheckRelatedActionAnyOf = "LOCATION_RESTRICTED_WITHOUT_RESPONSE"
)
