/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_Nudr_DR

// UpSecurity1 - Contains Userplain security information.
type UpSecurity1 struct {

	UpIntegr UpIntegrity `json:"upIntegr"`

	UpConfid UpConfidentiality `json:"upConfid"`
}
