/*
 * Ntsctsf_QoSandTSCAssistance Service API
 *
 * TSCTSF QoS and TSC Assistance Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_Ntsctsf_QoSandTSCAssistance

type SponsoringStatusAnyOf string

// List of SponsoringStatusAnyOf
const (
	DISABLED SponsoringStatusAnyOf = "SPONSOR_DISABLED"
	ENABLED SponsoringStatusAnyOf = "SPONSOR_ENABLED"
)
