/*
 * N32 Handshake API
 *
 * N32-c Handshake Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package N32_Handshake

// N32fErrorDetail - Details about the N32f error
type N32fErrorDetail struct {

	Attribute string `json:"attribute"`

	MsgReconstructFailReason FailureReason `json:"msgReconstructFailReason"`
}
