/*
 * 3gpp-mbs-ud-ingest
 *
 * API for MBS User Data Ingest Session.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package MBSUserDataIngestSession

type PktDistributionOperatingModeAnyOf string

// List of PktDistributionOperatingModeAnyOf
const (
	PROXY PktDistributionOperatingModeAnyOf = "PACKET_PROXY"
	FORWARD_ONLY PktDistributionOperatingModeAnyOf = "PACKET_FORWARD_ONLY"
)
