/*
 * MSGG_L3GDelivery
 *
 * API for MSGG L3G Message Delivery Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_MSGG_L3GDelivery

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// DeliverReportPost - deliver status report to Legacy 3GPP Message Gateway
func DeliverReportPost(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
