/*
 * LMF Location
 *
 * LMF Location Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package Nlmf_Location

// EventReportMessage - Indicates an event report message.
type EventReportMessage struct {

	EventClass EventClass `json:"eventClass"`

	EventContent RefToBinaryData `json:"eventContent"`
}
