/*
 * 3gpp-am-policyauthorization
 *
 * API for AM policy authorization.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_AMPolicyAuthorization

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// PostAppAmContexts - Creates a new Individual application AM Context resource
func PostAppAmContexts(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
