/*
 * Slice NRM
 *
 * OAS 3.0.1 specification of the Slice NRM @ 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 17.7.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_SliceNrm

type SynAvailability string

// List of SynAvailability
const (
	NOT_SUPPORTED SynAvailability = "NOT SUPPORTED"
	BETWEEN_BS_AND_UE SynAvailability = "BETWEEN BS AND UE"
	BETWEEN_BS_AND_UE__UE_AND_UE SynAvailability = "BETWEEN BS AND UE & UE AND UE"
)
