/*
 * EES EEL Managed ACR Service
 *
 * EES EEL Managed ACR Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package Eees_EELManagedACR

// ActStatusNotif - Represents an ACT status notification.
type ActStatusNotif struct {

	SubscriptionId string `json:"subscriptionId"`

	ActStatus ActResult `json:"actStatus"`
}
