/*
 * Nspaf_SecuredPacket
 *
 * Nspaf Secured Packet Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_Nspaf_SecuredPacket

// UiccConfigurationParameter - Represents UICC Configuration Parameters.
type UiccConfigurationParameter struct {

	// Represents a routing indicator.
	RoutingId string `json:"routingId,omitempty"`

	SteeringContainer []SteeringInfo `json:"steeringContainer,omitempty"`

	ExtendedSteeringContainer ExtendedSteeringContainer `json:"extendedSteeringContainer,omitempty"`
}
