/*
 * GBA BSF Nbsp_GBA Service
 *
 * GBA BSF Nbsp_GBA Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_Nbsp_GBA

// NafId - NAF ID, containing the NAF FQDN and the Ua Security Protocol Identifier
type NafId struct {

	// Fully Qualified Domain Name
	NafFqdn string `json:"nafFqdn"`

	UaSecProtId string `json:"uaSecProtId"`
}
