/*
 * 3gpp-msisdn-less-mo-sms
 *
 * API for MSISDN-less Mobile Originated SMS.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package MsisdnLessMoSms

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// DeliverMSISDNlessMOSMSNotification - Deliver a received MSIDN-less MO SMS from the SCEF to the SCS/AS.
func DeliverMSISDNlessMOSMSNotification(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
