/*
 * MSGS_MSGDelivery
 *
 * API for MSGG MSGin5G Server Message Delivery Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_MSGS_MSGDelivery

type AddressTypeAnyOf string

// List of AddressTypeAnyOf
const (
	UE AddressTypeAnyOf = "UE"
	AS AddressTypeAnyOf = "AS"
	GROUP AddressTypeAnyOf = "GROUP"
	BC AddressTypeAnyOf = "BC"
	TOPIC AddressTypeAnyOf = "TOPIC"
)
