/*
 * M1_EventDataProcessingProvisioning
 *
 * 5GMS AF M1 Event Data Processing Provisioning API © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package M1_EventDataProcessingProvisioning

type DataAccessProfileTimeAccessRestrictions struct {

	// indicating a time in seconds.
	Duration int32 `json:"duration"`

	AggregationFunctions []DataAggregationFunctionType `json:"aggregationFunctions"`
}
