/*
 * 3gpp-mo-lcs-notify
 *
 * API for UE updated location information notification.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.1.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package MoLcsNotify

// LdrType - Indicates LDR types.
type LdrType struct {
}
