/*
 * Eees Application Context Relocation Service
 *
 * Eees Application Context Relocation Service.   © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package Eees_AppContextRelocation

// EecCtxtReloc - Represents EEC Context relocation information.
type EecCtxtReloc struct {

	EecCtxtId string `json:"eecCtxtId"`

	SEesId string `json:"sEesId,omitempty"`

	SEecEndpoint EndPoint `json:"sEecEndpoint,omitempty"`

	TEesId string `json:"tEesId,omitempty"`

	TEecEndpoint EndPoint `json:"tEecEndpoint,omitempty"`
}
