/*
 * Namf_Communication
 *
 * AMF Communication Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package Namf_Communication

// EcRestrictionDataWb - Enhanced Coverage Restriction Data for WB-N1 mode
type EcRestrictionDataWb struct {

	EcModeARestricted bool `json:"ecModeARestricted,omitempty"`

	EcModeBRestricted bool `json:"ecModeBRestricted"`
}
