/*
 * Namf_Communication
 *
 * AMF Communication Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package Namf_Communication

// N1N2MsgTxfrErrDetail - N1/N2 Message Transfer Error Details
type N1N2MsgTxfrErrDetail struct {

	// Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
	RetryAfter int32 `json:"retryAfter,omitempty"`

	HighestPrioArp Arp `json:"highestPrioArp,omitempty"`

	// indicating a time in seconds.
	MaxWaitingTime int32 `json:"maxWaitingTime,omitempty"`
}
