/*
 * Namf_Communication
 *
 * AMF Communication Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package Namf_Communication

import (
	"time"
)

// ExpectedUeBehavior - Represents the expected UE behavior (e.g. UE moving trajectory) and its validity period
type ExpectedUeBehavior struct {

	ExpMoveTrajectory []UserLocation `json:"expMoveTrajectory"`

	// string with format 'date-time' as defined in OpenAPI.
	ValidityTime time.Time `json:"validityTime"`
}
