/*
 * Nchf_ConvergedCharging
 *
 * ConvergedCharging Service    © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 3.1.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package Nchf_ConvergedCharging

type SessionFailoverAnyOf string

// List of SessionFailoverAnyOf
const (
	NOT_SUPPORTED SessionFailoverAnyOf = "FAILOVER_NOT_SUPPORTED"
	SUPPORTED SessionFailoverAnyOf = "FAILOVER_SUPPORTED"
)
