/*
 * Nnsacf_SliceEventExposure
 *
 * Nnsacf_SliceEventExposure Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_Nnsacf_SliceEventExposure

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// CompleteModifySubscription - Nnsacf_SliceEventExposure Subscribe complete modify service Operation
func CompleteModifySubscription(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// DeleteSubscription - Nnsacf_SliceEventExposure Unsubscribe service Operation
func DeleteSubscription(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PartialModifySubscription - Nnsacf_SliceEventExposure Subscribe partial modify service Operation
func PartialModifySubscription(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
