/*
 * Nudm_EE
 *
 * Nudm Event Exposure Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_Nudm_EE

type FailedCauseAnyOf string

// List of FailedCauseAnyOf
const (
	AF_NOT_ALLOWED FailedCauseAnyOf = "AF_NOT_ALLOWED"
	MTC_PROVIDER_NOT_ALLOWED FailedCauseAnyOf = "MTC_PROVIDER_NOT_ALLOWED"
	MONITORING_NOT_ALLOWED FailedCauseAnyOf = "MONITORING_NOT_ALLOWED"
	UNSUPPORTED_MONITORING_EVENT_TYPE FailedCauseAnyOf = "UNSUPPORTED_MONITORING_EVENT_TYPE"
	UNSUPPORTED_MONITORING_REPORT_OPTIONS FailedCauseAnyOf = "UNSUPPORTED_MONITORING_REPORT_OPTIONS"
	UNSPECIFIED FailedCauseAnyOf = "UNSPECIFIED"
)
