/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_Nsmf_PDUSession

// SmContextRetrievedData - Data within Retrieve SM Context Response
type SmContextRetrievedData struct {

	// UE EPS PDN Connection container from SMF to AMF
	UeEpsPdnConnection string `json:"ueEpsPdnConnection"`

	SmContext SmContext `json:"smContext,omitempty"`

	SmallDataRateStatus SmallDataRateStatus `json:"smallDataRateStatus,omitempty"`

	ApnRateStatus ApnRateStatus `json:"apnRateStatus,omitempty"`

	DlDataWaitingInd bool `json:"dlDataWaitingInd,omitempty"`

	AfCoordinationInfo AfCoordinationInfo `json:"afCoordinationInfo,omitempty"`
}
