/*
 * Nucmf_UECapabilityManagement
 *
 * Nucmf_UECapabilityManagement Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_Nucmf_UERCM

type RacFormatAnyOf string

// List of RacFormatAnyOf
const (
	_5_GS RacFormatAnyOf = "5GS"
	EPS RacFormatAnyOf = "EPS"
)
