/*
 * 3gpp-eas-deployment
 *
 * API for AF provisioned EAS Deployment.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_EASDeployment

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// DeleteEDIs - Remove EAS Deployment Information based on given criteria.
func DeleteEDIs(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
