/*
 * GMDviaMBMSbyMB2
 *
 * API for Group Message Delivery via MBMS by MB2   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package GMDviaMBMSbyMB2

// Acknowledgement - Represents a successful acknowledgement of a notification.
type Acknowledgement struct {

	// A human-readable explanation specific to this successful acknowledgement
	Details string `json:"details"`
}
