/*
 * Nnwdaf_DataManagement
 *
 * Nnwdaf_DataManagement API Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_Nnwdaf_DataManagement

type ReachabilityForSmsConfigurationAnyOf string

// List of ReachabilityForSmsConfigurationAnyOf
const (
	NAS ReachabilityForSmsConfigurationAnyOf = "REACHABILITY_FOR_SMS_OVER_NAS"
	IP ReachabilityForSmsConfigurationAnyOf = "REACHABILITY_FOR_SMS_OVER_IP"
)
