/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.   
 *
 * API version: 1.4.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_CommonData

type PresenceStateAnyOf string

// List of PresenceStateAnyOf
const (
	IN_AREA PresenceStateAnyOf = "IN_AREA"
	OUT_OF_AREA PresenceStateAnyOf = "OUT_OF_AREA"
	UNKNOWN PresenceStateAnyOf = "UNKNOWN"
	INACTIVE PresenceStateAnyOf = "INACTIVE"
)
