/*
 * Data Collection and Reporting Common Data Types
 *
 * Data Collection and Reporting Common Data Types © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_CommonData

type DataCollectionClientType struct {
}
