/*
 * JOSE Protected Message Forwarding API
 *
 * N32-f Message Forwarding Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_JOSEProtectedMessageForwarding

type HttpMethodAnyOf string

// List of HttpMethodAnyOf
const (
	GET HttpMethodAnyOf = "GET"
	PUT HttpMethodAnyOf = "PUT"
	POST HttpMethodAnyOf = "POST"
	DELETE HttpMethodAnyOf = "DELETE"
	PATCH HttpMethodAnyOf = "PATCH"
	HEAD HttpMethodAnyOf = "HEAD"
	OPTIONS HttpMethodAnyOf = "OPTIONS"
	CONNECT HttpMethodAnyOf = "CONNECT"
	TRACE HttpMethodAnyOf = "TRACE"
)
