/*
 * Ntsctsf_ASTI Service API
 *
 * TSCTSF  Access Stratum time distribution configuration Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package Ntsctsf_ASTI

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// RequestStatusof5GAccessStratumTimeDistribution - Request the status of the 5G access stratum time distribution for a list of UEs.
func RequestStatusof5GAccessStratumTimeDistribution(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
