/*
 * Nmbsmf-MBSSession
 *
 * MB-SMF MBSSession Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package Nmbsmf_MBSSession

import (
	"time"
)

// ContextStatusEventReport - Context Status Event Report
type ContextStatusEventReport struct {

	EventType ContextStatusEventType `json:"eventType"`

	// string with format 'date-time' as defined in OpenAPI.
	TimeStamp time.Time `json:"timeStamp"`

	QosInfo QosInfo `json:"qosInfo,omitempty"`

	StatusInfo MbsSessionActivityStatus `json:"statusInfo,omitempty"`

	MbsServiceArea MbsServiceArea `json:"mbsServiceArea,omitempty"`

	// A map (list of key-value pairs) where the key identifies an areaSessionId 
	MbsServiceAreaInfoList map[string]MbsServiceAreaInfo `json:"mbsServiceAreaInfoList,omitempty"`

	MulticastTransAddInfo MulticastTransportAddressChangeInfo `json:"multicastTransAddInfo,omitempty"`

	MbsSecurityContext MbsSecurityContext `json:"mbsSecurityContext,omitempty"`
}
