/*
 * Nhss_imsSDM
 *
 * Nhss Subscriber Data Management Service for IMS.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.1.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_Nhss_imsSDM

// Ifcs - List of IFCs associated to the IMS public Identity
type Ifcs struct {

	IfcList []Ifc `json:"ifcList,omitempty"`

	CscfFilterSetIdList []int32 `json:"cscfFilterSetIdList,omitempty"`
}
