/*
 * Nhss_imsSDM
 *
 * Nhss Subscriber Data Management Service for IMS.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.1.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_Nhss_imsSDM

// ImsAssociatedIdentities - A list of identities belonging to the same Implicit Registration Set (IRS), along with the registration state of the IRS 
type ImsAssociatedIdentities struct {

	IrsState ImsRegistrationState `json:"irsState"`

	PublicIdentities PublicIdentities `json:"publicIdentities"`
}
