/*
 * Nhss_imsSDM
 *
 * Nhss Subscriber Data Management Service for IMS.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.1.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_Nhss_imsSDM

// CsgInformation - Information about a Closed Subscriber Group (CSG)
type CsgInformation struct {

	CsgId string `json:"csgId"`

	AccessMode string `json:"accessMode,omitempty"`

	CMi bool `json:"cMi,omitempty"`
}
