/*
 * Nhss_imsSDM
 *
 * Nhss Subscriber Data Management Service for IMS.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.1.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_Nhss_imsSDM

// DsaiTagInformation - DSAI tag information (list of DSAI tags activation state for an Application Server) 
type DsaiTagInformation struct {

	DsaiTagStatusList []DsaiTagStatus `json:"dsaiTagStatusList"`
}
