/*
 * Nnwdaf_AnalyticsInfo
 *
 * Nnwdaf_AnalyticsInfo Service API.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_Nnwdaf_AnalyticsInfo

// IwmscInfo - Information of an SMS-IWMSC NF Instance
type IwmscInfo struct {

	MsisdnRanges []IdentityRange `json:"msisdnRanges,omitempty"`

	SupiRanges []SupiRange `json:"supiRanges,omitempty"`

	TaiRangeList []TaiRange `json:"taiRangeList,omitempty"`

	ScNumber string `json:"scNumber,omitempty"`
}
