/*
 * UAE Server C2 Operation Mode Management Service
 *
 * UAE Server C2 Operation Mode Management Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package UAE_C2OperationModeManagement

// SelectedC2CommModeNotif - Represents information on the C2 Communication Mode selected by a UAS (i.e. pair of UAV and UAV-C). 
type SelectedC2CommModeNotif struct {

	UasId UasId `json:"uasId"`

	SelPrimaryC2CommMode C2CommMode `json:"selPrimaryC2CommMode"`

	SelSecondaryC2CommMode C2CommMode `json:"selSecondaryC2CommMode,omitempty"`
}
