/*
 * UAE Server C2 Operation Mode Management Service
 *
 * UAE Server C2 Operation Mode Management Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package UAE_C2OperationModeManagement

type C2CommModeAnyOf string

// List of C2CommModeAnyOf
const (
	DIRECT_C2_COMMUNICATION C2CommModeAnyOf = "DIRECT_C2_COMMUNICATION"
	NETWORK_ASSISTED_C2_COMMUNICATION C2CommModeAnyOf = "NETWORK_ASSISTED_C2_COMMUNICATION"
	UTM_NAVIGATED_C2_COMMUNICATION C2CommModeAnyOf = "UTM_NAVIGATED_C2_COMMUNICATION"
)
