/*
 * Nnsacf_NSAC
 *
 * Nnsacf_NSAC Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_Nnsacf_NSAC

type EacModeAnyOf string

// List of EacModeAnyOf
const (
	ACTIVE EacModeAnyOf = "ACTIVE"
	DEACTIVE EacModeAnyOf = "DEACTIVE"
)
