/*
 * Nnsacf_NSAC
 *
 * Nnsacf_NSAC Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_Nnsacf_NSAC

// AcuFailureReason - Failure Reason of ACU operation to an S-NSSAI. Possible values are - SLICE_NOT_FOUND - EXCEED_MAX_UE_NUM - EXCEED_MAX_UE_NUM_3GPP - EXCEED_MAX_UE_NUM_N3GPP - EXCEED_MAX_PDU_NUM - EXCEED_MAX_PDU_NUM_3GPP - EXCEED_MAX_PDU_NUM_N3GPP 
type AcuFailureReason struct {
}
