/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package Nudm_SDM

type Lpi struct {

	LocationPrivacyInd LocationPrivacyInd `json:"locationPrivacyInd"`

	ValidTimePeriod ValidTimePeriod `json:"validTimePeriod,omitempty"`
}
