/*
 * Unified Data Repository Service API file for subscription data
 *
 * Unified Data Repository Service (subscription data).   The API version is defined in 3GPP TS 29.504.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: -
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_Subscription_Data

type AppPortId struct {

	// Integer where the allowed values correspond to the value range of an unsigned 16-bit integer.
	DestinationPort int32 `json:"destinationPort,omitempty"`

	// Integer where the allowed values correspond to the value range of an unsigned 16-bit integer.
	OriginatorPort int32 `json:"originatorPort,omitempty"`
}
