/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.   
 *
 * API version: 1.4.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package CommonData

// ExternalMbsServiceArea - List of geographic area or list of civic address info for MBS Service Area
type ExternalMbsServiceArea struct {

	GeographicAreaList []GeographicArea `json:"geographicAreaList,omitempty"`

	CivicAddressList []CivicAddress `json:"civicAddressList,omitempty"`
}
