/*
 * Common Data Types
 *
 * Common Data Types for Service Based Interfaces.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.   
 *
 * API version: 1.4.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package CommonData

type ReportingTriggerAnyOf string

// List of ReportingTriggerAnyOf
const (
	PERIODICAL ReportingTriggerAnyOf = "PERIODICAL"
	EVENT_A2 ReportingTriggerAnyOf = "EVENT_A2"
	EVENT_A2_PERIODIC ReportingTriggerAnyOf = "EVENT_A2_PERIODIC"
	ALL_RRM_EVENT_TRIGGERS ReportingTriggerAnyOf = "ALL_RRM_EVENT_TRIGGERS"
)
