/*
 * 3gpp-racs-parameter-provisioning
 *
 * API for provisioning UE radio capability parameters.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package RacsParameterProvisioning

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// CreateRACSParameterProvisioning - Create a new RACS parameter provisioning.
func CreateRACSParameterProvisioning(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// FetchAllRACSParameterProvisionings - Read all RACS parameter provisionings for a given AF.
func FetchAllRACSParameterProvisionings(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
