/*
 * 3gpp-cp-parameter-provisioning
 *
 * API for provisioning communication pattern parameters.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package CpProvisioning

// CpReport - Represents a CP report indicating the CP set identifier(s) which CP parameter(s) are not added or modified successfully and the corresponding failure cause(s).
type CpReport struct {

	// Identifies the CP set identifier(s) which CP parameter(s) are not added or modified successfully
	SetIds []string `json:"setIds,omitempty"`

	FailureCode CpFailureCode `json:"failureCode"`
}
