/*
 * 3gpp-pfd-management
 *
 * API for PFD management.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package PfdManagement

// PfdReport - Represents a PFD report indicating the external application identifier(s) which PFD(s) are not added or modified successfully and the corresponding failure cause(s).
type PfdReport struct {

	// Identifies the external application identifier(s) which PFD(s) are not added or modified successfully
	ExternalAppIds []string `json:"externalAppIds"`

	FailureCode FailureCode `json:"failureCode"`

	// Unsigned integer identifying a period of time in units of seconds.
	CachingTime int32 `json:"cachingTime,omitempty"`

	LocationArea UserPlaneLocationArea `json:"locationArea,omitempty"`
}
