/*
 * CAPIF_Auditing_API
 *
 * API for auditing.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package CAPIF_Auditing_API

// Protocol - Possible values are: - HTTP_1_1: HTTP version 1.1 - HTTP_2: HTTP version 2 
type Protocol struct {
}
