/*
 * ECS Target EES Discovery API
 *
 * API for Target EES Discovery.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_Eecs_TargetEESDiscovery

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// EesProfilesGet - 
func EesProfilesGet(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
