/*
 * Intent NRM
 *
 * OAS 3.0.1 definition of the Intent NRM © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 17.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package IntentNrm

type NotFulfilledState string

// List of NotFulfilledState
const (
	ACKNOWLEDGED NotFulfilledState = "ACKNOWLEDGED"
	COMPLIANT NotFulfilledState = "COMPLIANT"
	DEGRADED NotFulfilledState = "DEGRADED"
	SUSPENDED NotFulfilledState = "SUSPENDED"
	TERMINATED NotFulfilledState = "TERMINATED"
	FULFILMENTFAILED NotFulfilledState = "FULFILMENTFAILED"
)
