/*
 * Intent NRM
 *
 * OAS 3.0.1 definition of the Intent NRM © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 17.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package IntentNrm

type Condition string

// List of Condition
const (
	EQUAL_TO Condition = "Is_equal_to"
	LESS_THAN Condition = "Is_less_than"
	GREATER_THAN Condition = "Is_greater_than"
	WITHIN_THE_RANGE Condition = "Is_within_the_range"
)
