/*
 * Npcf_UEPolicyControl
 *
 * UE Policy Control Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package Npcf_UEPolicyControl

type CmStateAnyOf string

// List of CmStateAnyOf
const (
	IDLE CmStateAnyOf = "IDLE"
	CONNECTED CmStateAnyOf = "CONNECTED"
)
