/*
 * SS_NetworkResourceAdaptation
 *
 * SS Network Resource Adaptation Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package SS_NetworkResourceAdaptation

type ServiceAnnoucementModeAnyOf string

// List of ServiceAnnoucementModeAnyOf
const (
	NRM ServiceAnnoucementModeAnyOf = "NRM"
	VAL ServiceAnnoucementModeAnyOf = "VAL"
)
