/*
 * Nhss_imsUECM
 *
 * Nhss UE Context Management Service for IMS.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_Nhss_imsUECM

// ScscfRestorationInfoResponse - S-CSCF restoration information response
type ScscfRestorationInfoResponse struct {

	ScscfRestorationInfoResponse []ScscfRestorationInfo `json:"scscfRestorationInfoResponse,omitempty"`
}
