/*
 * SS_NetworkResourceMonitoring
 *
 * API for SEAL Network Resource Monitoring.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_SS_NetworkResourceMonitoring

// MeasurementData - Presents the aggregated measurement data.
type MeasurementData struct {

	// Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
	DlDelay int32 `json:"dlDelay,omitempty"`

	// Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
	UlDelay int32 `json:"ulDelay,omitempty"`

	// Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
	RtDelay int32 `json:"rtDelay,omitempty"`

	// Unsigned integer indicating Packet Loss Rate (see clauses 5.7.2.8 and 5.7.4 of 3GPP TS 23.501), expressed in tenth of percent. 
	AvgPlr int32 `json:"avgPlr,omitempty"`

	// String representing a bit rate; the prefixes follow the standard symbols from The International System of Units, and represent x1000 multipliers, with the exception that prefix \"K\" is used to represent the standard symbol \"k\". 
	AvgDataRate string `json:"avgDataRate,omitempty"`

	// String representing a bit rate; the prefixes follow the standard symbols from The International System of Units, and represent x1000 multipliers, with the exception that prefix \"K\" is used to represent the standard symbol \"k\". 
	MaxDataRate string `json:"maxDataRate,omitempty"`

	// Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
	AvrDlTrafficVol int32 `json:"avrDlTrafficVol,omitempty"`

	// Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
	AvrUlTrafficVol int32 `json:"avrUlTrafficVol,omitempty"`
}
