/*
 * Nmbstf-distsession
 *
 * MBSTF Distribution Session Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package Nmbstf_DistSession

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// Destroy - Deletes an individual MBS distribution session resource in the MBSTF.
func Destroy(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// Retrieve - Retrieves an individual MBS distribution session resource in the MBSTF.
func Retrieve(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// Update - Updates an individual MBS distribution session resource in the MBSTF.
func Update(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
