/*
 * SS_NetworkResourceMonitoring
 *
 * API for SEAL Network Resource Monitoring.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package SS_NetworkResourceMonitoring

// MonitoringSubscription - The unicast monitoring subscription request.
type MonitoringSubscription struct {

	// List of VAL UEs whose QoS monitoring data is requested.
	ValUeIds []ValTargetUe `json:"valUeIds,omitempty"`

	// The VAL Group Id which QoS monitoring data is requested.
	ValGroupId string `json:"valGroupId,omitempty"`

	// List of VAL streams for which QoS monitoring data is requested.
	ValStreamIds []string `json:"valStreamIds,omitempty"`

	MeasReqs MeasurementRequirements `json:"measReqs,omitempty"`

	MonRep MonitoringReport `json:"monRep,omitempty"`

	ReportReqs ReportingRequirements `json:"reportReqs,omitempty"`

	// String providing an URI formatted according to RFC 3986.
	NotifUri string `json:"notifUri,omitempty"`

	ReqTestNotif bool `json:"reqTestNotif,omitempty"`

	WsNotifCfg WebsockNotifConfig `json:"wsNotifCfg,omitempty"`

	// A string used to indicate the features supported by an API that is used as defined in clause  6.6 in 3GPP TS 29.500. The string shall contain a bitmask indicating supported features in  hexadecimal representation Each character in the string shall take a value of \"0\" to \"9\",  \"a\" to \"f\" or \"A\" to \"F\" and shall represent the support of 4 features as described in  table 5.2.2-3. The most significant character representing the highest-numbered features shall  appear first in the string, and the character representing features 1 to 4 shall appear last  in the string. The list of features and their numbering (starting with 1) are defined  separately for each API. If the string contains a lower number of characters than there are  defined features for an API, all features that would be represented by characters that are not  present in the string are not supported. 
	SuppFeat string `json:"suppFeat,omitempty"`
}
