/*
 * Nnwdaf_MLModelProvision
 *
 * Nnwdaf_MLModelProvision API Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package Nnwdaf_MLModelProvision

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// CreateNWDAFMLModelProvisionSubcription - Create a new Individual NWDAF ML Model Provision Subscription resource.
func CreateNWDAFMLModelProvisionSubcription(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
