/*
 * ECS EES Registration_API
 *
 * API for EES Registration.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package Eecs_EESRegistration

import (
	"time"
)

// EesRegistrationPatch - Represents partial update request of individual EES registration information.
type EesRegistrationPatch struct {

	EesProf EesProfile `json:"eesProf,omitempty"`

	// string with format 'date-time' as defined in OpenAPI with 'nullable:true' property.  
	ExpTime *time.Time `json:"expTime,omitempty"`
}
