/*
 * UAE Server C2 Operation Mode Management Service
 *
 * UAE Server C2 Operation Mode Management Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_UAE_C2OperationModeManagement

// C2CommModeSwitchNotif - Represents information on the targeted C2 Communication Mode switching for a UAS (i.e. pair of UAV and UAV-C). 
type C2CommModeSwitchNotif struct {

	// string providing an URI formatted according to IETF RFC 3986.
	UaeServerId string `json:"uaeServerId"`

	UasId UasId `json:"uasId"`

	C2CommModeSwitchType C2CommModeSwitching `json:"c2CommModeSwitchType"`

	SwitchingCause C2SwitchingCause `json:"switchingCause,omitempty"`
}
