/*
 * UAE Server C2 Operation Mode Management Service
 *
 * UAE Server C2 Operation Mode Management Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_UAE_C2OperationModeManagement

// C2SwitchPolicies - Represents the C2 operation mode switching policies.
type C2SwitchPolicies struct {

	DirectC2LinkQualityThrlds C2LinkQualityThrlds `json:"directC2LinkQualityThrlds,omitempty"`

	UuC2LinkQualityThrlds C2LinkQualityThrlds `json:"uuC2LinkQualityThrlds,omitempty"`
}
