/*
 * Ntsctsf_QoSandTSCAssistance Service API
 *
 * TSCTSF QoS and TSC Assistance Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package Ntsctsf_QoSandTSCAssistance

type TscEventAnyOf string

// List of TscEventAnyOf
const (
	FAILED_RESOURCES_ALLOCATION TscEventAnyOf = "FAILED_RESOURCES_ALLOCATION"
	QOS_MONITORING TscEventAnyOf = "QOS_MONITORING"
	QOS_GUARANTEED TscEventAnyOf = "QOS_GUARANTEED"
	QOS_NOT_GUARANTEED TscEventAnyOf = "QOS_NOT_GUARANTEED"
	SUCCESSFUL_RESOURCES_ALLOCATION TscEventAnyOf = "SUCCESSFUL_RESOURCES_ALLOCATION"
	USAGE_REPORT TscEventAnyOf = "USAGE_REPORT"
)
