/*
 * Ntsctsf_QoSandTSCAssistance Service API
 *
 * TSCTSF QoS and TSC Assistance Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package Ntsctsf_QoSandTSCAssistance

type FlowDirectionAnyOf string

// List of FlowDirectionAnyOf
const (
	DOWNLINK FlowDirectionAnyOf = "DOWNLINK"
	UPLINK FlowDirectionAnyOf = "UPLINK"
	BIDIRECTIONAL FlowDirectionAnyOf = "BIDIRECTIONAL"
	UNSPECIFIED FlowDirectionAnyOf = "UNSPECIFIED"
)
