/*
 * UAE Server Real-time UAV Status Service
 *
 * UAE Server Real-time UAV Status Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package UAE_RealtimeUAVStatus

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// DeleteRTUavStatusSubscription - Request the deletion of an existing real-time UAV status subscription.
func DeleteRTUavStatusSubscription(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetRTUavStatusSubscription - Retrieve a real-time UAV status subscription resource.
func GetRTUavStatusSubscription(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UpdateRTUavStatusSubscription - Request the update of an existing real-time UAV status subscription.
func UpdateRTUavStatusSubscription(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
