/*
 * SS_UserProfileRetrieval
 *
 * API for SEAL User Profile Retrieval.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.1.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_SS_UserProfileRetrieval

// ProfileDoc - Represents Profile information associated with a VAL user ID or a VAL UE ID.
type ProfileDoc struct {

	// Profile information associated with the valUserId or valUeId.
	ProfileInformation string `json:"profileInformation"`

	ValTgtUe ValTargetUe `json:"valTgtUe"`
}
