/*
 * NRF Bootstrapping
 *
 * NRF Bootstrapping.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package Nnrf_Bootstrapping

type StatusAnyOf string

// List of StatusAnyOf
const (
	OPERATIVE StatusAnyOf = "OPERATIVE"
	NON_OPERATIVE StatusAnyOf = "NON_OPERATIVE"
)
