/*
 * M5_ServiceAccessInformation
 *
 * 5GMS AF M5 Service Access Information API © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_M5_ServiceAccessInformation

// M5EasRelocationRequirements - Relocation requirements of an EAS.
type M5EasRelocationRequirements struct {

	Tolerance EasRelocationTolerance `json:"tolerance"`

	// Unsigned Integer, i.e. only value 0 and integers above 0 are permissible with the OpenAPI 'nullable: true' property. 
	MaxInterruptionDuration *int32 `json:"maxInterruptionDuration,omitempty"`
}
