/*
 * Npcf_PolicyAuthorization Service API
 *
 * PCF Policy Authorization Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_Npcf_PolicyAuthorization

type FlowStatusAnyOf string

// List of FlowStatusAnyOf
const (
	ENABLED_UPLINK FlowStatusAnyOf = "ENABLED-UPLINK"
	ENABLED_DOWNLINK FlowStatusAnyOf = "ENABLED-DOWNLINK"
	ENABLED FlowStatusAnyOf = "ENABLED"
	DISABLED FlowStatusAnyOf = "DISABLED"
	REMOVED FlowStatusAnyOf = "REMOVED"
)
