/*
 * SS_Events
 *
 * API for SEAL Events management.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.1.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_SS_Events

// MonLocAreaInterestFltr - Filter information indicate the area of interest and triggering events.
type MonLocAreaInterestFltr struct {

	LocInfoCri LocationInfoCriteria `json:"locInfoCri"`

	// Triggering events when to send information.
	TrigEvnts []MonLocTriggerEvent `json:"trigEvnts,omitempty"`
}
