/*
 * SS_Events
 *
 * API for SEAL Events management.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.1.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_SS_Events

// MonitorEvents - List of event types to be monitored in the context of events monitoring service.
type MonitorEvents struct {

	// List of monitoring events related to VAL UE.
	CnEvnts []MonitoringType `json:"cnEvnts,omitempty"`

	// List of analytics events related to VAL UE.
	AnlEvnts []AnalyticsEvent `json:"anlEvnts,omitempty"`
}
