/*
 * M1_EdgeResourcesProvisioning
 *
 * 5GMS AF M1 Edge Resources Provisioning API © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_M1_EdgeResourcesProvisioning

// EasRequirements - Requirements of an EAS.
type EasRequirements struct {

	EasProviderIds []string `json:"easProviderIds"`

	EasType string `json:"easType"`

	EasFeatures []string `json:"easFeatures"`

	ServiceKpi EasServiceKpi `json:"serviceKpi,omitempty"`

	ServiceArea GeographicalServiceArea `json:"serviceArea,omitempty"`

	ServiceAvailabilitySchedule []ScheduledCommunicationTime `json:"serviceAvailabilitySchedule"`

	ServiceContinuityScenarios []AcrScenario `json:"serviceContinuityScenarios"`

	ServiceContinuitySupport []AcrScenario `json:"serviceContinuitySupport,omitempty"`
}
