/*
 * 3gpp-ecr-control
 *
 * API for enhanced converage restriction control.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ECRControl

// PlmnEcRestrictionDataWb - Indicates whether enhanced coverage mode is restricted or not for a PLMN ID.
type PlmnEcRestrictionDataWb struct {

	PlmnId PlmnId `json:"plmnId"`

	PlmnEcrDataWb EcRestrictionDataWb `json:"plmnEcrDataWb,omitempty"`
}
