/*
 * VAE_HDMapDynamicInfo
 *
 * API for VAE HDMapDynamicInfo Service   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package VAE_HDMapDynamicInfo

type LineTypeAnyOf string

// List of LineTypeAnyOf
const (
	DSL LineTypeAnyOf = "DSL"
	PON LineTypeAnyOf = "PON"
)
