/*
 * CAPIF_API_Invoker_Management_API
 *
 * API for API invoker management.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_CAPIF_API_Invoker_Management_API

// OnboardingNotification - Represents a notification of on-boarding or update result.
type OnboardingNotification struct {

	// Set to \"true\" indicate successful on-boarding. Otherwise set to \"false\"
	Result bool `json:"result"`

	// string providing an URI formatted according to IETF RFC 3986.
	ResourceLocation string `json:"resourceLocation,omitempty"`

	ApiInvokerEnrolmentDetails ApiInvokerEnrolmentDetails `json:"apiInvokerEnrolmentDetails,omitempty"`

	// The list of service APIs that the API Invoker is allowed to invoke
	ApiList []ServiceApiDescription `json:"apiList,omitempty"`
}
