/*
 * 3gpp-as-session-with-qos
 *
 * API for setting us an AS session with required QoS.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_AsSessionWithQoS

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// DeleteIndASSessionWithQoSSubscription - Deletes an already existing subscription.
func DeleteIndASSessionWithQoSSubscription(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// FetchIndASSessionWithQoSSubscription - Read an active subscriptions for the SCS/AS and the subscription Id.
func FetchIndASSessionWithQoSSubscription(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// ModifyIndASSessionWithQoSSubscription - Updates/replaces an existing subscription resource.
func ModifyIndASSessionWithQoSSubscription(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UpdateIndASSessionWithQoSSubscription - Updates/replaces an existing subscription resource.
func UpdateIndASSessionWithQoSSubscription(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
