/*
 * VAE_MessageDelivery
 *
 * API for VAE Message Delivery Service   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package VAE_MessageDelivery

import (
	"time"
)

// DownlinkMessageDeliveryData - Contains the downlink V2X message delivery data.
type DownlinkMessageDeliveryData struct {

	// Represents the identifier of the V2X UE.
	UeId string `json:"ueId,omitempty"`

	// Represents the group ID for which a V2X message is addressed.
	GroupId string `json:"groupId,omitempty"`

	// string with format 'date-time' as defined in OpenAPI.
	Duration time.Time `json:"duration,omitempty"`

	// Represents a geographical area identifier.
	GeoId string `json:"geoId,omitempty"`

	// string with format 'bytes' as defined in OpenAPI
	Payload string `json:"payload"`
}
