/*
 * Ndcaf_DataReportingProvisioning
 *
 * Data Collection AF: Provisioning Sessions API © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_Ndcaf_DataReportingProvisioning

type DataCollectionClientTypeAnyOf string

// List of DataCollectionClientTypeAnyOf
const (
	DIRECT DataCollectionClientTypeAnyOf = "DIRECT"
	INDIRECT DataCollectionClientTypeAnyOf = "INDIRECT"
	APPLICATION_SERVER DataCollectionClientTypeAnyOf = "APPLICATION_SERVER"
)
