/*
 * MSGG_N3GDelivery
 *
 * API for MSGG N3G Message Delivery Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package MSGG_N3GDelivery

type ReportDeliveryStatusAnyOf string

// List of ReportDeliveryStatusAnyOf
const (
	SUCCESS ReportDeliveryStatusAnyOf = "REPT_DELY_SUCCESS"
	FAILED ReportDeliveryStatusAnyOf = "REPT_DELY_FAILED"
)
