/*
 * 3gpp-akma
 *
 * API for Naanf_AKMA.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_Naanf_AKMA

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// RegisterAKMAKey - Store AKMA related key material.
func RegisterAKMAKey(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
