/*
 * Npcf_MBSPolicyControl API
 *
 * MBS Policy Control Service   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_Npcf_MBSPolicyControl

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// UpdateIndMBSPolicy - Request the update of an existing MBS Policy Association.
func UpdateIndMBSPolicy(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
