/*
 * Npcf_MBSPolicyControl API
 *
 * MBS Policy Control Service   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_Npcf_MBSPolicyControl

// MbsPccRuleStatus - Possible values are - ACTIVE: Indicates that the MBS PCC rule(s) are successfully installed. - INACTIVE: Indicates that the MBS PCC rule(s) are removed. 
type MbsPccRuleStatus struct {
}
