/*
 * Ndccf_DataManagement
 *
 * DCCF Data Management Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package Ndccf_DataManagement

// VendorSpecificFeature - Information about a vendor-specific feature
type VendorSpecificFeature struct {

	FeatureName string `json:"featureName"`

	FeatureVersion string `json:"featureVersion"`
}
