/*
 * Ndccf_DataManagement
 *
 * DCCF Data Management Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package Ndccf_DataManagement

type 5GsUserStateAnyOf string

// List of 5GsUserStateAnyOf
const (
	DEREGISTERED 5GsUserStateAnyOf = "DEREGISTERED"
	CONNECTED_NOT_REACHABLE_FOR_PAGING 5GsUserStateAnyOf = "CONNECTED_NOT_REACHABLE_FOR_PAGING"
	CONNECTED_REACHABLE_FOR_PAGING 5GsUserStateAnyOf = "CONNECTED_REACHABLE_FOR_PAGING"
	NOT_PROVIDED_FROM_AMF 5GsUserStateAnyOf = "NOT_PROVIDED_FROM_AMF"
)
