/*
 * Nhss_gbaUEAU
 *
 * Nhss UE Authentication Service for GBA.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_Nhss_gbaUEAU

// DigestAuthentication - Parameters used for the Digest authentication scheme
type DigestAuthentication struct {

	DigestRealm string `json:"digestRealm"`

	DigestAlgorithm DigestAlgorithm `json:"digestAlgorithm"`

	DigestQop DigestQop `json:"digestQop"`

	Ha1 string `json:"ha1"`
}
