/*
 * Nnef_PFDmanagement Service API
 *
 * Packet Flow Description Management Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_Nnef_PFDmanagement

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// NnefPFDmanagementModifySubscr - Updates/replaces an existing subscription resource
func NnefPFDmanagementModifySubscr(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// NnefPFDmanagementUnsubscribe - Delete a subscription of PFD change notification.
func NnefPFDmanagementUnsubscribe(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
