/*
 * EES EAS Registration_API
 *
 * API for EAS Registration.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package Eees_EASRegistration

// EasCategory - Possible values are: - UAS: Category of EAS is for Uncrewed Aerial Services. - V2X: Category of EAS is for V2X Services. - OTHER: Any other type of EAS category. 
type EasCategory struct {
}
