/*
 * AI/ML NRM
 *
 * OAS 3.0.1 specification of the AI/ML NRM © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 17.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package AiMlNrm

type RequestStatus string

// List of RequestStatus
const (
	NOT_STARTED RequestStatus = "NOT_STARTED"
	TRAINING_IN_PROGRESS RequestStatus = "TRAINING_IN_PROGRESS"
	SUSPENDED RequestStatus = "SUSPENDED"
	FINISHED RequestStatus = "FINISHED"
	CANCELLED RequestStatus = "CANCELLED"
)
