/*
 * 3gpp-mbs-us
 *
 * API for MBS User Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package MBSUserService

// MbsUserServicePatch - Represents the requested modifications to the parameters of an MBS User Service. 
type MbsUserServicePatch struct {

	ExtServiceIds []string `json:"extServiceIds,omitempty"`

	// String providing an URI formatted according to RFC 3986.
	ServClass string `json:"servClass,omitempty"`

	ServAnnModes []ServiceAnnouncementMode `json:"servAnnModes,omitempty"`

	ServNameDescs []ServiceNameDescription `json:"servNameDescs,omitempty"`

	MainServLang string `json:"mainServLang,omitempty"`
}
