/*
 * Nnwdaf_AnalyticsInfo
 *
 * Nnwdaf_AnalyticsInfo Service API.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package Nnwdaf_AnalyticsInfo

// EventFilter - Represents the event filters used to identify the requested analytics.
type EventFilter struct {

	// FALSE represents not applicable for all slices. TRUE represents applicable for all slices. 
	AnySlice bool `json:"anySlice,omitempty"`

	// Identification(s) of network slice.
	Snssais []Snssai `json:"snssais,omitempty"`

	AppIds []string `json:"appIds,omitempty"`

	Dnns []string `json:"dnns,omitempty"`

	Dnais []string `json:"dnais,omitempty"`

	// Identification(s) of LADN DNN to indicate the LADN service area as the AOI.
	LadnDnns []string `json:"ladnDnns,omitempty"`

	NetworkArea NetworkAreaInfo `json:"networkArea,omitempty"`

	VisitedAreas []NetworkAreaInfo `json:"visitedAreas,omitempty"`

	// Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
	MaxTopAppUlNbr int32 `json:"maxTopAppUlNbr,omitempty"`

	// Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
	MaxTopAppDlNbr int32 `json:"maxTopAppDlNbr,omitempty"`

	NfInstanceIds []string `json:"nfInstanceIds,omitempty"`

	NfSetIds []string `json:"nfSetIds,omitempty"`

	NfTypes []NfType `json:"nfTypes,omitempty"`

	NsiIdInfos []NsiIdInfo `json:"nsiIdInfos,omitempty"`

	QosRequ QosRequirement `json:"qosRequ,omitempty"`

	NwPerfTypes []NetworkPerfType `json:"nwPerfTypes,omitempty"`

	BwRequs []BwRequirement `json:"bwRequs,omitempty"`

	ExcepIds []ExceptionId `json:"excepIds,omitempty"`

	ExptAnaType ExpectedAnalyticsType `json:"exptAnaType,omitempty"`

	ExptUeBehav ExpectedUeBehaviourData `json:"exptUeBehav,omitempty"`

	RatFreqs []RatFreqInformation `json:"ratFreqs,omitempty"`

	DisperReqs []DispersionRequirement `json:"disperReqs,omitempty"`

	RedTransReqs []RedundantTransmissionExpReq `json:"redTransReqs,omitempty"`

	WlanReqs []WlanPerformanceReq `json:"wlanReqs,omitempty"`

	ListOfAnaSubsets []AnalyticsSubset `json:"listOfAnaSubsets,omitempty"`

	UpfInfo UpfInformation `json:"upfInfo,omitempty"`

	AppServerAddrs []AddrFqdn `json:"appServerAddrs,omitempty"`

	DnPerfReqs []DnPerformanceReq `json:"dnPerfReqs,omitempty"`
}
