/*
 * Nnwdaf_AnalyticsInfo
 *
 * Nnwdaf_AnalyticsInfo Service API.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package Nnwdaf_AnalyticsInfo

type N1MessageClassAnyOf string

// List of N1MessageClassAnyOf
const (
	_5_GMM N1MessageClassAnyOf = "5GMM"
	SM N1MessageClassAnyOf = "SM"
	LPP N1MessageClassAnyOf = "LPP"
	SMS N1MessageClassAnyOf = "SMS"
	UPDP N1MessageClassAnyOf = "UPDP"
	LCS N1MessageClassAnyOf = "LCS"
)
