/*
 * Nnwdaf_AnalyticsInfo
 *
 * Nnwdaf_AnalyticsInfo Service API.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package Nnwdaf_AnalyticsInfo

type ScpCapabilityAnyOf string

// List of ScpCapabilityAnyOf
const (
	INDIRECT_COM_WITH_DELEG_DISC ScpCapabilityAnyOf = "INDIRECT_COM_WITH_DELEG_DISC"
)
