/*
 * Nnwdaf_AnalyticsInfo
 *
 * Nnwdaf_AnalyticsInfo Service API.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package Nnwdaf_AnalyticsInfo

// AdditionInfoAnalyticsInfoRequest - Indicates additional information why the analytics request is rejected.
type AdditionInfoAnalyticsInfoRequest struct {

	// indicating a time in seconds.
	RvWaitTime int32 `json:"rvWaitTime,omitempty"`
}
