/*
 * Ngmlc_Location
 *
 * GMLC Location Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.1.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package Ngmlc_Location

type LcsQosClassAnyOf string

// List of LcsQosClassAnyOf
const (
	BEST_EFFORT LcsQosClassAnyOf = "BEST_EFFORT"
	ASSURED LcsQosClassAnyOf = "ASSURED"
	MULTIPLE_QOS LcsQosClassAnyOf = "MULTIPLE_QOS"
)
