/*
 * Ngmlc_Location
 *
 * GMLC Location Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.1.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package Ngmlc_Location

type FailureCauseAnyOf string

// List of FailureCauseAnyOf
const (
	POSITIONING_DENIED FailureCauseAnyOf = "POSITIONING_DENIED"
	UNSUPPORTED_BY_UE FailureCauseAnyOf = "UNSUPPORTED_BY_UE"
	NOT_REGISTED_UE FailureCauseAnyOf = "NOT_REGISTED_UE"
	UNSPECIFIED FailureCauseAnyOf = "UNSPECIFIED"
)
