/*
 * TS 28.532 Streaming data reporting service
 *
 * OAS 3.0.1 specification for the Streaming data reporting service (Streaming MnS) © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 17.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package StreamingDataMnS
// TimeToTriggerL1Type : See details in 3GPP TS 32.422 clause 5.10.Z.
type TimeToTriggerL1Type string

// List of TimeToTriggerL1Type
const (
	_0MS TimeToTriggerL1Type = "0ms"
	_40MS TimeToTriggerL1Type = "40ms"
	_64MS TimeToTriggerL1Type = "64ms"
	_80MS TimeToTriggerL1Type = "80ms"
	_100MS TimeToTriggerL1Type = "100ms"
	_128MS TimeToTriggerL1Type = "128ms"
	_160MS TimeToTriggerL1Type = "160ms"
	_256MS TimeToTriggerL1Type = "256ms"
	_320MS TimeToTriggerL1Type = "320ms"
	_480MS TimeToTriggerL1Type = "480ms"
	_512MS TimeToTriggerL1Type = "512ms"
	_640MS TimeToTriggerL1Type = "640ms"
	_1024MS TimeToTriggerL1Type = "1024ms"
	_1280MS TimeToTriggerL1Type = "1280ms"
	_2560MS TimeToTriggerL1Type = "2560ms"
	_5120MS TimeToTriggerL1Type = "5120ms"
)
