/*
 * Nnssaaf_NSSAA
 *
 * Network Slice-Specific Authentication and Authorization Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_Nnssaaf_NSSAA

// NfType - NF types known to NRF
type NfType struct {
}
