/*
 * 3gpp-traffic-influence
 *
 * API for AF traffic influence   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_TrafficInfluence

// SubscribedEvent - Possible values are: - UP_PATH_CHANGE: The AF requests to be notified when the UP path changes for the PDU session. 
type SubscribedEvent struct {
}
