/*
 * NR NRM
 *
 * OAS 3.0.1 specification of the NR NRM © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 17.7.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_NrNrm

type FrequencyDomainPara struct {

	RimRSSubcarrierSpacing int32 `json:"rimRSSubcarrierSpacing,omitempty"`

	RIMRSBandwidth int32 `json:"rIMRSBandwidth,omitempty"`

	NrofGlobalRIMRSFrequencyCandidates int32 `json:"nrofGlobalRIMRSFrequencyCandidates,omitempty"`

	RimRSCommonCarrierReferencePoint int32 `json:"rimRSCommonCarrierReferencePoint,omitempty"`

	RimRSStartingFrequencyOffsetIdList []int32 `json:"rimRSStartingFrequencyOffsetIdList,omitempty"`
}
