/*
 * NR NRM
 *
 * OAS 3.0.1 specification of the NR NRM © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 17.7.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_NrNrm

type NrCellDuSingleAllOf1 struct {

	RRMPolicyRatio []RrmPolicyRatioSingle `json:"RRMPolicyRatio,omitempty"`

	CPCIConfigurationFunction CpciConfigurationFunctionSingle `json:"CPCIConfigurationFunction,omitempty"`

	DRACHOptimizationFunction DrachOptimizationFunctionSingle `json:"DRACHOptimizationFunction,omitempty"`

	NrOperatorCellDu []NrOperatorCellDuSingle `json:"NrOperatorCellDu,omitempty"`
}
