/*
 * NR NRM
 *
 * OAS 3.0.1 specification of the NR NRM © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 17.7.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_NrNrm

type ExternalGnbDuFunctionSingle struct {

	Id *string `json:"id"`

	ObjectClass string `json:"objectClass,omitempty"`

	ObjectInstance string `json:"objectInstance,omitempty"`

	VsDataContainer []VsDataContainerSingle `json:"VsDataContainer,omitempty"`

	Attributes ManagedFunctionAttr `json:"attributes,omitempty"`

	PerfMetricJob []PerfMetricJobSingle `json:"PerfMetricJob,omitempty"`

	ThresholdMonitor []ThresholdMonitorSingle `json:"ThresholdMonitor,omitempty"`

	ManagedNFService []ManagedNfServiceSingle `json:"ManagedNFService,omitempty"`

	TraceJob []TraceJobSingle `json:"TraceJob,omitempty"`

	EPF1C []EpF1CSingle `json:"EP_F1C,omitempty"`

	EPF1U []EpF1USingle `json:"EP_F1U,omitempty"`
}
