/*
 * NR NRM
 *
 * OAS 3.0.1 specification of the NR NRM © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 17.7.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_NrNrm

type ExternalGnbCuUpFunctionSingleAllOf struct {

	EPE1 []EpE1Single `json:"EP_E1,omitempty"`

	EPF1U []EpF1USingle `json:"EP_F1U,omitempty"`

	EPXnU []EpXnUSingle `json:"EP_XnU,omitempty"`
}
