/*
 * NR NRM
 *
 * OAS 3.0.1 specification of the NR NRM © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 17.7.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_NrNrm

type GnbDuFunctionSingleAllOf1 struct {

	RRMPolicyRatio []RrmPolicyRatioSingle `json:"RRMPolicyRatio,omitempty"`

	NrCellDu []NrCellDuSingle `json:"NrCellDu,omitempty"`

	BwpMultiple []BwpSingle `json:"Bwp-Multiple,omitempty"`

	NrSectorCarrierMultiple []NrSectorCarrierSingle `json:"NrSectorCarrier-Multiple,omitempty"`

	EPF1C EpF1CSingle `json:"EP_F1C,omitempty"`

	EPF1U []EpF1USingle `json:"EP_F1U,omitempty"`

	DRACHOptimizationFunction DrachOptimizationFunctionSingle `json:"DRACHOptimizationFunction,omitempty"`

	OperatorDU []OperatorDuSingle `json:"OperatorDU,omitempty"`

	BWPSet []BwpSetSingle `json:"BWPSet,omitempty"`
}
