/*
 * Nnef_EASDeployment
 *
 * NEF EAS Deployment service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_Nnef_EASDeployment

// EasDepNotification - Represents the EAS Deployment Notifcation.
type EasDepNotification struct {

	EasDepInfo EasDeployInfoData `json:"easDepInfo"`

	EventId EasEvent `json:"eventId"`
}
