/*
 * MDA NRM
 *
 * OAS 3.0.1 specification of the MDA NRM © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 17.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_MdaNrm

type MbsfnArea struct {

	MbsfnAreaId int32 `json:"mbsfnAreaId,omitempty"`

	Earfcn int32 `json:"earfcn,omitempty"`
}
