/*
 * Nchf_OfflineOnlyCharging
 *
 * OfflineOnlyCharging Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_Nchf_OfflineOnlyCharging

type FailureHandlingAnyOf string

// List of FailureHandlingAnyOf
const (
	TERMINATE FailureHandlingAnyOf = "TERMINATE"
	CONTINUE FailureHandlingAnyOf = "CONTINUE"
	RETRY_AND_TERMINATE FailureHandlingAnyOf = "RETRY_AND_TERMINATE"
)
