/*
 * Nchf_OfflineOnlyCharging
 *
 * OfflineOnlyCharging Service © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_Nchf_OfflineOnlyCharging

// PduSessionType - PduSessionType indicates the type of a PDU session. It shall comply with the provisions defined in table 5.4.3.3-1.  
type PduSessionType struct {
}
