/*
 * 3gpp-monitoring-event
 *
 * API for Monitoring Event.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_MonitoringEvent

// LocationFailureCause - This string Indicates the location positioning failure cause. Possible values are - POSITIONING_DENIED: Positioning is denied. - UNSUPPORTED_BY_UE: Positioning is not supported by UE. - NOT_REGISTED_UE: UE is not registered. - UNSPECIFIED: Unspecified. 
type LocationFailureCause struct {
}
