/*
 * 3gpp-monitoring-event
 *
 * API for Monitoring Event.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_MonitoringEvent

// ConsentRevocNotif - Represents the user consent revocation information conveyed in a user consent revocation notification. 
type ConsentRevocNotif struct {

	SubscriptionId string `json:"subscriptionId"`

	ConsentsRevoked []ConsentRevoked `json:"consentsRevoked"`
}
