/*
 * 3gpp-monitoring-event
 *
 * API for Monitoring Event.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_MonitoringEvent

import (
	"time"
)

// IdleStatusInfo - Represents the information relevant to when the UE transitions into idle mode.
type IdleStatusInfo struct {

	// Unsigned integer identifying a period of time in units of seconds.
	ActiveTime int32 `json:"activeTime,omitempty"`

	EdrxCycleLength float32 `json:"edrxCycleLength,omitempty"`

	// Identifies the number of packets shall be buffered in the serving gateway. It shall be present if the idle status indication is requested by the SCS/AS with \"idleStatusIndication\" in the \"monitoringEventSubscription\" sets to \"true\".
	SuggestedNumberOfDlPackets int32 `json:"suggestedNumberOfDlPackets,omitempty"`

	// string with format \"date-time\" as defined in OpenAPI.
	IdleStatusTimestamp time.Time `json:"idleStatusTimestamp,omitempty"`

	// Unsigned integer identifying a period of time in units of seconds.
	PeriodicAUTimer int32 `json:"periodicAUTimer,omitempty"`
}
