/*
 * Nudm_UECM
 *
 * Nudm Context Management Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_Nudm_UECM

type UeReachableIndAnyOf string

// List of UeReachableIndAnyOf
const (
	REACHABLE UeReachableIndAnyOf = "REACHABLE"
	NOT_REACHABLE UeReachableIndAnyOf = "NOT_REACHABLE"
	UNKNOWN UeReachableIndAnyOf = "UNKNOWN"
)
