/*
 * Nudm_UECM
 *
 * Nudm Context Management Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_Nudm_UECM

type RegistrationDataSets struct {

	Amf3Gpp Amf3GppAccessRegistration `json:"amf3Gpp,omitempty"`

	AmfNon3Gpp AmfNon3GppAccessRegistration `json:"amfNon3Gpp,omitempty"`

	SmfRegistration SmfRegistrationInfo `json:"smfRegistration,omitempty"`

	Smsf3Gpp SmsfRegistration `json:"smsf3Gpp,omitempty"`

	SmsfNon3Gpp SmsfRegistration `json:"smsfNon3Gpp,omitempty"`

	IpSmGw IpSmGwRegistration `json:"ipSmGw,omitempty"`

	NwdafRegistration NwdafRegistrationInfo `json:"nwdafRegistration,omitempty"`
}
