/*
 * Namf_Communication
 *
 * AMF Communication Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_Namf_Communication

// PwsErrorData - Data related to PWS error included in a N2 Information Transfer failure response
type PwsErrorData struct {

	NamfCause int32 `json:"namfCause"`
}
