/*
 * Namf_Communication
 *
 * AMF Communication Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_Namf_Communication

type PolicyReqTriggerAnyOf string

// List of PolicyReqTriggerAnyOf
const (
	LOCATION_CHANGE PolicyReqTriggerAnyOf = "LOCATION_CHANGE"
	PRA_CHANGE PolicyReqTriggerAnyOf = "PRA_CHANGE"
	ALLOWED_NSSAI_CHANGE PolicyReqTriggerAnyOf = "ALLOWED_NSSAI_CHANGE"
	NWDAF_DATA_CHANGE PolicyReqTriggerAnyOf = "NWDAF_DATA_CHANGE"
	PLMN_CHANGE PolicyReqTriggerAnyOf = "PLMN_CHANGE"
	CON_STATE_CHANGE PolicyReqTriggerAnyOf = "CON_STATE_CHANGE"
	SMF_SELECT_CHANGE PolicyReqTriggerAnyOf = "SMF_SELECT_CHANGE"
	ACCESS_TYPE_CHANGE PolicyReqTriggerAnyOf = "ACCESS_TYPE_CHANGE"
)
