/*
 * Namf_Communication
 *
 * AMF Communication Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_Namf_Communication

// AmfEventSubscriptionAddInfo - Additional information received for an AMF event subscription, e.g. binding indications
type AmfEventSubscriptionAddInfo struct {

	BindingInfo []string `json:"bindingInfo,omitempty"`

	SubscribingNfType NfType `json:"subscribingNfType,omitempty"`

	EventSyncInd bool `json:"eventSyncInd,omitempty"`

	NfConsumerInfo []string `json:"nfConsumerInfo,omitempty"`
}
