/*
 * Namf_Communication
 *
 * AMF Communication Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_Namf_Communication

// MmContext - Represents a Mobility Management Context in UE Context
type MmContext struct {

	AccessType AccessType `json:"accessType"`

	NasSecurityMode NasSecurityMode `json:"nasSecurityMode,omitempty"`

	EpsNasSecurityMode EpsNasSecurityMode `json:"epsNasSecurityMode,omitempty"`

	// Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
	NasDownlinkCount int32 `json:"nasDownlinkCount,omitempty"`

	// Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
	NasUplinkCount int32 `json:"nasUplinkCount,omitempty"`

	// string with format 'bytes' as defined in OpenAPI
	UeSecurityCapability string `json:"ueSecurityCapability,omitempty"`

	// string with format 'bytes' as defined in OpenAPI
	S1UeNetworkCapability string `json:"s1UeNetworkCapability,omitempty"`

	AllowedNssai []Snssai `json:"allowedNssai,omitempty"`

	NssaiMappingList []NssaiMapping `json:"nssaiMappingList,omitempty"`

	AllowedHomeNssai []Snssai `json:"allowedHomeNssai,omitempty"`

	NsInstanceList []string `json:"nsInstanceList,omitempty"`

	ExpectedUEbehavior ExpectedUeBehavior `json:"expectedUEbehavior,omitempty"`

	UeDifferentiationInfo UeDifferentiationInfo `json:"ueDifferentiationInfo,omitempty"`

	// string with format 'bytes' as defined in OpenAPI
	PlmnAssiUeRadioCapId string `json:"plmnAssiUeRadioCapId,omitempty"`

	// string with format 'bytes' as defined in OpenAPI
	ManAssiUeRadioCapId string `json:"manAssiUeRadioCapId,omitempty"`

	UcmfDicEntryId string `json:"ucmfDicEntryId,omitempty"`

	N3IwfId GlobalRanNodeId `json:"n3IwfId,omitempty"`

	WagfId GlobalRanNodeId `json:"wagfId,omitempty"`

	TngfId GlobalRanNodeId `json:"tngfId,omitempty"`

	AnN2ApId int32 `json:"anN2ApId,omitempty"`

	NssaaStatusList []NssaaStatus `json:"nssaaStatusList,omitempty"`

	PendingNssaiMappingList []NssaiMapping `json:"pendingNssaiMappingList,omitempty"`

	UuaaMmStatus UuaaMmStatus `json:"uuaaMmStatus,omitempty"`
}
