/*
 * Ndccf_ContextManagement
 *
 * DCCF Context Management Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package Ndccf_ContextManagement

type NetworkNodeDiameterAddress struct {

	// Fully Qualified Domain Name
	Name string `json:"name"`

	// Fully Qualified Domain Name
	Realm string `json:"realm"`
}
