/*
 * Ndccf_ContextManagement
 *
 * DCCF Context Management Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package Ndccf_ContextManagement

// SnssaiEasdfInfoItem - Set of parameters supported by EASDF for a given S-NSSAI
type SnssaiEasdfInfoItem struct {

	SNssai ExtSnssai `json:"sNssai"`

	DnnEasdfInfoList []DnnEasdfInfoItem `json:"dnnEasdfInfoList"`
}
