/*
 * Ndccf_ContextManagement
 *
 * DCCF Context Management Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package Ndccf_ContextManagement

type N2InformationClassAnyOf string

// List of N2InformationClassAnyOf
const (
	SM N2InformationClassAnyOf = "SM"
	NRPPA N2InformationClassAnyOf = "NRPPa"
	PWS N2InformationClassAnyOf = "PWS"
	PWS_BCAL N2InformationClassAnyOf = "PWS-BCAL"
	PWS_RF N2InformationClassAnyOf = "PWS-RF"
	RAN N2InformationClassAnyOf = "RAN"
	V2_X N2InformationClassAnyOf = "V2X"
	PROSE N2InformationClassAnyOf = "PROSE"
)
