/*
 * Ndccf_ContextManagement
 *
 * DCCF Context Management Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package Ndccf_ContextManagement

type DnaiChangeTypeAnyOf string

// List of DnaiChangeTypeAnyOf
const (
	EARLY DnaiChangeTypeAnyOf = "EARLY"
	EARLY_LATE DnaiChangeTypeAnyOf = "EARLY_LATE"
	LATE DnaiChangeTypeAnyOf = "LATE"
)
