/*
 * Nmfaf_3caDataManagement
 *
 * MFAF 3GPP Consumer Adaptor (3CA) Data Management Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_Nmfaf_3caDataManagement

// SnssaiSmfInfoItem - Set of parameters supported by SMF for a given S-NSSAI
type SnssaiSmfInfoItem struct {

	SNssai ExtSnssai `json:"sNssai"`

	DnnSmfInfoList []DnnSmfInfoItem `json:"dnnSmfInfoList"`
}
