/*
 * Nnef_EventExposure
 *
 * NEF Event Exposure Service.   © 2022 , 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package Nnef_EventExposure

type NefEventAnyOf string

// List of NefEventAnyOf
const (
	SVC_EXPERIENCE NefEventAnyOf = "SVC_EXPERIENCE"
	UE_MOBILITY NefEventAnyOf = "UE_MOBILITY"
	UE_COMM NefEventAnyOf = "UE_COMM"
	EXCEPTIONS NefEventAnyOf = "EXCEPTIONS"
	USER_DATA_CONGESTION NefEventAnyOf = "USER_DATA_CONGESTION"
	PERF_DATA NefEventAnyOf = "PERF_DATA"
	DISPERSION NefEventAnyOf = "DISPERSION"
	COLLECTIVE_BEHAVIOUR NefEventAnyOf = "COLLECTIVE_BEHAVIOUR"
	MS_QOE_METRICS NefEventAnyOf = "MS_QOE_METRICS"
	MS_CONSUMPTION NefEventAnyOf = "MS_CONSUMPTION"
	MS_NET_ASSIST_INVOCATION NefEventAnyOf = "MS_NET_ASSIST_INVOCATION"
	MS_DYN_POLICY_INVOCATION NefEventAnyOf = "MS_DYN_POLICY_INVOCATION"
	MS_ACCESS_ACTIVITY NefEventAnyOf = "MS_ACCESS_ACTIVITY"
)
