/*
 * Nnwdaf_DataManagement
 *
 * Nnwdaf_DataManagement API Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package Nnwdaf_DataManagement

type DlDataDeliveryStatusAnyOf string

// List of DlDataDeliveryStatusAnyOf
const (
	BUFFERED DlDataDeliveryStatusAnyOf = "BUFFERED"
	TRANSMITTED DlDataDeliveryStatusAnyOf = "TRANSMITTED"
	DISCARDED DlDataDeliveryStatusAnyOf = "DISCARDED"
)
