/*
 * Neasdf_DNSContext
 *
 * EASDF DNS Context Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package Neasdf_DNSContext

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// DeleteDnsContext - Delete the DNS Context
func DeleteDnsContext(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// ReplaceDnsContext - Updates the DNS context (complete replacement)
func ReplaceDnsContext(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UpdateDnsContext - Updates the DNS context
func UpdateDnsContext(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
