/*
 * Neasdf_DNSContext
 *
 * EASDF DNS Context Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package Neasdf_DNSContext

// FqdnPatternMatchingRule - a matching rule for a FQDN pattern
type FqdnPatternMatchingRule struct {

	Regex string `json:"regex,omitempty"`

	StringMatchingRule StringMatchingRule `json:"stringMatchingRule,omitempty"`
}
