/*
 * Nsmf_NIDD
 *
 * SMF NIDD Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_Nsmf_NIDD

// DeliverReqData - Representation of the payload of a Deliver Request.
type DeliverReqData struct {

	MtData RefToBinaryData `json:"mtData"`
}
