/*
 * Nnwdaf_MLModelProvision
 *
 * Nnwdaf_MLModelProvision API Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_Nnwdaf_MLModelProvision

import (
	"time"
)

// MlEventSubscription - Represents a subscription to a single event.
type MlEventSubscription struct {

	MLEvent NwdafEvent `json:"mLEvent"`

	MLEventFilter EventFilter `json:"mLEventFilter"`

	TgtUe TargetUeInformation `json:"tgtUe,omitempty"`

	MLTargetPeriod TimeWindow `json:"mLTargetPeriod,omitempty"`

	// string with format 'date-time' as defined in OpenAPI.
	ExpiryTime time.Time `json:"expiryTime,omitempty"`
}
