/*
 * Nnwdaf_MLModelProvision
 *
 * Nnwdaf_MLModelProvision API Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_Nnwdaf_MLModelProvision

// NwdafMlModelProvNotif - Represents notifications on events that occurred.
type NwdafMlModelProvNotif struct {

	// Notifications about Individual Events.
	EventNotifs []MlEventNotif `json:"eventNotifs"`

	// String identifying a subscription to the Nnwdaf_MLModelProvision Service.
	SubscriptionId string `json:"subscriptionId"`
}
