/*
 * Nnef_SMContext
 *
 * Nnef SMContext Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_Nnef_SMContext

// SmallDataRateControl - Configuration of Small Data Rate Control for the SM Context.
type SmallDataRateControl struct {

	TimeUnit SmallDataRateControlTimeUnit `json:"timeUnit"`

	MaxPacketRateUl int32 `json:"maxPacketRateUl,omitempty"`

	MaxPacketRateDl int32 `json:"maxPacketRateDl,omitempty"`

	MaxAdditionalPacketRateUl int32 `json:"maxAdditionalPacketRateUl,omitempty"`

	MaxAdditionalPacketRateDl int32 `json:"maxAdditionalPacketRateDl,omitempty"`
}
