/*
 * Nadrf_DataManagement
 *
 * ADRF Data Management Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package Nadrf_DataManagement

type DispersionOrderingCriterionAnyOf string

// List of DispersionOrderingCriterionAnyOf
const (
	TIME_SLOT_START DispersionOrderingCriterionAnyOf = "TIME_SLOT_START"
	DISPERSION DispersionOrderingCriterionAnyOf = "DISPERSION"
	CLASSIFICATION DispersionOrderingCriterionAnyOf = "CLASSIFICATION"
	RANKING DispersionOrderingCriterionAnyOf = "RANKING"
	PERCENTILE_RANKING DispersionOrderingCriterionAnyOf = "PERCENTILE_RANKING"
)
