/*
 * Nadrf_DataManagement
 *
 * ADRF Data Management Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package Nadrf_DataManagement

// AmfEventSubsSyncInfo - AMF Event Subscriptions Information for synchronization
type AmfEventSubsSyncInfo struct {

	SubscriptionList []AmfEventSubscriptionInfo `json:"subscriptionList"`
}
