/*
 * Nadrf_DataManagement
 *
 * ADRF Data Management Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package Nadrf_DataManagement

type MatchingDirectionAnyOf string

// List of MatchingDirectionAnyOf
const (
	ASCENDING MatchingDirectionAnyOf = "ASCENDING"
	DESCENDING MatchingDirectionAnyOf = "DESCENDING"
	CROSSED MatchingDirectionAnyOf = "CROSSED"
)
