/*
 * Nadrf_DataManagement
 *
 * ADRF Data Management Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package Nadrf_DataManagement

// NefEventFilter - Represents event filter information for an event.
type NefEventFilter struct {

	TgtUe TargetUeIdentification `json:"tgtUe"`

	AppIds []string `json:"appIds,omitempty"`

	LocArea NetworkAreaInfo `json:"locArea,omitempty"`

	CollAttrs []CollectiveBehaviourFilter `json:"collAttrs,omitempty"`
}
