/*
 * Nadrf_DataManagement
 *
 * ADRF Data Management Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package Nadrf_DataManagement

// NadrfStoredDataSpec - Contains information about Data or Analytics specification.
type NadrfStoredDataSpec struct {

	DataSpec DataSubscription `json:"dataSpec,omitempty"`

	AnaSpec NnwdafEventsSubscription `json:"anaSpec,omitempty"`

	TimePeriod TimeWindow `json:"timePeriod"`
}
