/*
 * nmbsf-mbs-us
 *
 * API for MBS User Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package Nmbsf_MBSUserService

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// CreateMBSUserService - Request the creation of a new MBS User Service.
func CreateMBSUserService(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// RetrieveMBSUserServices - Retrieve all the active MBS User Service resources managed by the MBSF.
func RetrieveMBSUserServices(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
