/*
 * GMDviaMBMSbyxMB
 *
 * API for Group Message Delivery via MBMS by xMB   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_GMDviaMBMSbyxMB

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// CreateGMDViaMBMS - Creates a new delivery via MBMS for a given SCS/AS and a service Id.
func CreateGMDViaMBMS(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// FetchAllGMDViaMBMS - Read all group message delivery via MBMS resource for a given SCS/AS and a service id.
func FetchAllGMDViaMBMS(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
