/*
 * GMDviaMBMSbyxMB
 *
 * API for Group Message Delivery via MBMS by xMB   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_GMDviaMBMSbyxMB

import (
	"time"
)

// GmdViaMbmsByxMbPatch - Represents a modification request of a group message delivery via MBMS by xMB.
type GmdViaMbmsByxMbPatch struct {

	MbmsLocArea MbmsLocArea `json:"mbmsLocArea,omitempty"`

	// string with format \"date-time\" as defined in OpenAPI.
	MessageDeliveryStartTime time.Time `json:"messageDeliveryStartTime,omitempty"`

	// string with format \"date-time\" as defined in OpenAPI.
	MessageDeliveryStopTime time.Time `json:"messageDeliveryStopTime,omitempty"`

	// String with format \"byte\" as defined in OpenAPI Specification, i.e, base64-encoded characters.
	GroupMessagePayload string `json:"groupMessagePayload,omitempty"`

	// string formatted according to IETF RFC 3986 identifying a referenced resource.
	NotificationDestination string `json:"notificationDestination,omitempty"`
}
