/*
 * Npcf_SMPolicyControl API
 *
 * Session Management Policy Control Service   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package Npcf_SMPolicyControl

type ReportingLevelAnyOf string

// List of ReportingLevelAnyOf
const (
	SER_ID_LEVEL ReportingLevelAnyOf = "SER_ID_LEVEL"
	RAT_GR_LEVEL ReportingLevelAnyOf = "RAT_GR_LEVEL"
	SPON_CON_LEVEL ReportingLevelAnyOf = "SPON_CON_LEVEL"
)
