/*
 * VAE_SessionOrientedService
 *
 * API for VAE_SessionOrientedService   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_VAE_SessionOrientedService

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// SubscriptionsSubscriptionIdPut - Updates/replaces an existing subscription resource
func SubscriptionsSubscriptionIdPut(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
