/*
 * SS_GroupManagement
 *
 * API for SEAL Group management.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.1.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package SS_GroupManagement

// GeographicalCoordinates - Geographical coordinates.
type GeographicalCoordinates struct {

	Lon float64 `json:"lon"`

	Lat float64 `json:"lat"`
}
