/*
 * Nnsacf_NSAC
 *
 * Nnsacf_NSAC Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package Nnsacf_NSAC

type UeAcRequestData struct {

	UeACRequestInfo []UeAcRequestInfo `json:"ueACRequestInfo"`

	// String uniquely identifying a NF instance. The format of the NF Instance ID shall be a  Universally Unique Identifier (UUID) version 4, as described in IETF RFC 4122.  
	NfId string `json:"nfId"`

	NfType NfType `json:"nfType,omitempty"`

	// String providing an URI formatted according to RFC 3986.
	EacNotificationUri string `json:"eacNotificationUri,omitempty"`
}
