/*
 * Eees_ACREvents
 *
 * API for ACR events subscription and notification. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package Eees_ACREvents

import (
	"time"
)

// AcrEventsSubscriptionPatch - An individual ACR events subscription resource to be updated.
type AcrEventsSubscriptionPatch struct {

	// string with format \"date-time\" as defined in OpenAPI.
	ExpTime time.Time `json:"expTime,omitempty"`

	// The list of application identifiers of the EASs.
	EasIds []string `json:"easIds,omitempty"`

	EventIds AcrEventIds `json:"eventIds,omitempty"`

	// string providing an URI formatted according to IETF RFC 3986.
	NotificationDestination string `json:"notificationDestination,omitempty"`
}
