/*
 * Nnef_EventExposure
 *
 * NEF Event Exposure Service.   © 2022 , 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_Nnef_EventExposure

// MsConsumptionCollection - Contains the Media Streaming Consumption information collected for an UE Application via AF. 
type MsConsumptionCollection struct {

	MsConsumps []string `json:"msConsumps"`
}
