/*
 * 3gpp-time-sync-exposure
 *
 * API for time synchronization exposure.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_TimeSyncExposure

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// DeleteAnConfiguration - Deletes an already existing configuration
func DeleteAnConfiguration(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// FullyUpdateAnConfiguration - Fully updates/replaces an existing configuration resource
func FullyUpdateAnConfiguration(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
