/*
 * 3gpp-time-sync-exposure
 *
 * API for time synchronization exposure.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_TimeSyncExposure

type GmCapableAnyOf string

// List of GmCapableAnyOf
const (
	GPTP GmCapableAnyOf = "GPTP"
	PTP GmCapableAnyOf = "PTP"
)
