/*
 * 3gpp-analyticsexposure
 *
 * API for Analytics Exposure.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.1.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package AnalyticsExposure

// AnalyticsEventFilterSubsc - Represents an analytics event filter.
type AnalyticsEventFilterSubsc struct {

	NwPerfReqs []NetworkPerfRequirement `json:"nwPerfReqs,omitempty"`

	LocArea LocationArea5G `json:"locArea,omitempty"`

	AppIds []string `json:"appIds,omitempty"`

	// String representing a Data Network as defined in clause 9A of 3GPP TS 23.003;  it shall contain either a DNN Network Identifier, or a full DNN with both the Network  Identifier and Operator Identifier, as specified in 3GPP TS 23.003 clause 9.1.1 and 9.1.2. It shall be coded as string in which the labels are separated by dots  (e.g. \"Label1.Label2.Label3\"). 
	Dnn string `json:"dnn,omitempty"`

	Dnais []string `json:"dnais,omitempty"`

	ExcepRequs []Exception `json:"excepRequs,omitempty"`

	ExptAnaType ExpectedAnalyticsType `json:"exptAnaType,omitempty"`

	ExptUeBehav ExpectedUeBehaviourData `json:"exptUeBehav,omitempty"`

	MatchingDir MatchingDirection `json:"matchingDir,omitempty"`

	ReptThlds []ThresholdLevel `json:"reptThlds,omitempty"`

	Snssai Snssai `json:"snssai,omitempty"`

	NsiIdInfos []NsiIdInfo `json:"nsiIdInfos,omitempty"`

	QosReq QosRequirement `json:"qosReq,omitempty"`

	QosFlowRetThds []RetainabilityThreshold `json:"qosFlowRetThds,omitempty"`

	RanUeThrouThds []string `json:"ranUeThrouThds,omitempty"`

	DisperReqs []DispersionRequirement `json:"disperReqs,omitempty"`

	ListOfAnaSubsets []AnalyticsSubset `json:"listOfAnaSubsets,omitempty"`

	DnPerfReqs []DnPerformanceReq `json:"dnPerfReqs,omitempty"`

	BwRequs []BwRequirement `json:"bwRequs,omitempty"`

	RatFreqs []RatFreqInformation `json:"ratFreqs,omitempty"`

	AppServerAddrs []AddrFqdn `json:"appServerAddrs,omitempty"`

	ExtraReportReq EventReportingRequirement `json:"extraReportReq,omitempty"`

	// Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
	MaxNumOfTopAppUl int32 `json:"maxNumOfTopAppUl,omitempty"`

	// Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
	MaxNumOfTopAppDl int32 `json:"maxNumOfTopAppDl,omitempty"`

	VisitedLocAreas []LocationArea5G `json:"visitedLocAreas,omitempty"`
}
