/*
 * Npcf_AMPolicyAuthorization Service API
 *
 * PCF Access and Mobility Policy Authorization Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_Npcf_AMPolicyAuthorization

type AmEventAnyOf string

// List of AmEventAnyOf
const (
	SAC_CH AmEventAnyOf = "SAC_CH"
	PDUID_CH AmEventAnyOf = "PDUID_CH"
)
