/*
 * LMF Location
 *
 * LMF Location Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_Nlmf_Location

type ReportingAccessTypeAnyOf string

// List of ReportingAccessTypeAnyOf
const (
	NR ReportingAccessTypeAnyOf = "NR"
	EUTRA_CONNECTED_TO_5_GC ReportingAccessTypeAnyOf = "EUTRA_CONNECTED_TO_5GC"
	NON_3_GPP_CONNECTED_TO_5_GC ReportingAccessTypeAnyOf = "NON_3GPP_CONNECTED_TO_5GC"
	NR_LEO ReportingAccessTypeAnyOf = "NR_LEO"
	NR_MEO ReportingAccessTypeAnyOf = "NR_MEO"
	NR_GEO ReportingAccessTypeAnyOf = "NR_GEO"
	NR_OTHER_SAT ReportingAccessTypeAnyOf = "NR_OTHER_SAT"
)
