/*
 * Nadrf_DataManagement
 *
 * ADRF Data Management Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_Nadrf_DataManagement

// NwdafCapability - Indicates the capability supported by the NWDAF
type NwdafCapability struct {

	AnalyticsAggregation bool `json:"analyticsAggregation,omitempty"`

	AnalyticsMetadataProvisioning bool `json:"analyticsMetadataProvisioning,omitempty"`
}
