/*
 * Unified Data Repository Service API file for structured data for exposure
 *
 * The API version is defined in 3GPP TS 29.504   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: -
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package Exposure_Data

type RatTypeAnyOf string

// List of RatTypeAnyOf
const (
	NR RatTypeAnyOf = "NR"
	EUTRA RatTypeAnyOf = "EUTRA"
	WLAN RatTypeAnyOf = "WLAN"
	VIRTUAL RatTypeAnyOf = "VIRTUAL"
	NBIOT RatTypeAnyOf = "NBIOT"
	WIRELINE RatTypeAnyOf = "WIRELINE"
	WIRELINE_CABLE RatTypeAnyOf = "WIRELINE_CABLE"
	WIRELINE_BBF RatTypeAnyOf = "WIRELINE_BBF"
	LTE_M RatTypeAnyOf = "LTE-M"
	NR_U RatTypeAnyOf = "NR_U"
	EUTRA_U RatTypeAnyOf = "EUTRA_U"
	TRUSTED_N3_GA RatTypeAnyOf = "TRUSTED_N3GA"
	TRUSTED_WLAN RatTypeAnyOf = "TRUSTED_WLAN"
	UTRA RatTypeAnyOf = "UTRA"
	GERA RatTypeAnyOf = "GERA"
	NR_LEO RatTypeAnyOf = "NR_LEO"
	NR_MEO RatTypeAnyOf = "NR_MEO"
	NR_GEO RatTypeAnyOf = "NR_GEO"
	NR_OTHER_SAT RatTypeAnyOf = "NR_OTHER_SAT"
	NR_REDCAP RatTypeAnyOf = "NR_REDCAP"
)
