/*
 * Npcf_AMPolicyAuthorization Service API
 *
 * PCF Access and Mobility Policy Authorization Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package Npcf_AMPolicyAuthorization

import (
	"time"
)

// PduidInformation - Contains the ProSe Discovery UE ID and its validity timer.
type PduidInformation struct {

	// string with format 'date-time' as defined in OpenAPI.
	Expiry time.Time `json:"expiry"`

	// Contains the PDUID.
	Pduid string `json:"pduid"`
}
