/*
 * VAE_ApplicationRequirement
 *
 * API for VAE Application Requirement Service   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_VAE_ApplicationRequirement

// ServiceLevel - Indicates a service level for application service.
type ServiceLevel struct {
}
