/*
 * VAE_DynamicGroup
 *
 * VAE_Dynamic_Group Service   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_VAE_DynamicGroup

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// DeleteGroupConfiguration - VAE Group Configuration resource delete service Operation
func DeleteGroupConfiguration(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// ReadDynamicGroupConfiguration - VAE Group Configuration resource read service Operation
func ReadDynamicGroupConfiguration(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
