/*
 * UAE Server Real-time UAV Status Service
 *
 * UAE Server Real-time UAV Status Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_UAE_RealtimeUAVStatus

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// CreateRTUavStatusSubsc - Request the creation of a subscription to real-time UAV status reporting.
func CreateRTUavStatusSubsc(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetRTUavStatusSubscriptions - Retrieve all the active real-time UAV status subscriptions managed by the UAE Server.
func GetRTUavStatusSubscriptions(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
