/*
 * VAE_ApplicationRequirement
 *
 * API for VAE Application Requirement Service   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package VAE_ApplicationRequirement

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// DeleteApplicationRequirement - VAE Application Requirement resource delete service Operation
func DeleteApplicationRequirement(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// ReadApplicationRequirement - VAE Application Requirement resource read service Operation
func ReadApplicationRequirement(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
