/*
 * Nnwdaf_EventsSubscription
 *
 * Nnwdaf_EventsSubscription Service API.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_Nnwdaf_EventsSubscription

// DispersionRequirement - Represents the dispersion analytics requirements.
type DispersionRequirement struct {

	DisperType DispersionType `json:"disperType"`

	ClassCriters []ClassCriterion `json:"classCriters,omitempty"`

	RankCriters []RankingCriterion `json:"rankCriters,omitempty"`

	DispOrderCriter DispersionOrderingCriterion `json:"dispOrderCriter,omitempty"`

	Order MatchingDirection `json:"order,omitempty"`
}
