/*
 * Nnwdaf_EventsSubscription
 *
 * Nnwdaf_EventsSubscription Service API.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_Nnwdaf_EventsSubscription

// TransferRequestType - Possible values are: - PREPARE: Indicates that the request is for analytics subscription transfer preparation. - TRANSFER: Indicates that the request is for analytics subscription transfer execution. 
type TransferRequestType struct {
}
