/*
 * nmbsf-mbs-us
 *
 * API for MBS User Service. © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_Nmbsf_MBSUserService

// MbsServiceType - Indicates the type of an MBS session
type MbsServiceType struct {
}
