/*
 * 3gpp-network-parameter-configuration
 *
 * API for network parameter configuration.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.2.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_NpConfiguration

// ConfigurationNotification - Represents a configuration result notification.
type ConfigurationNotification struct {

	// string formatted according to IETF RFC 3986 identifying a referenced resource.
	Configuration string `json:"configuration"`

	// The grouping configuration result notification provided by the SCEF.
	ConfigResults []ConfigResult `json:"configResults,omitempty"`

	AppliedParam AppliedParameterConfiguration `json:"appliedParam,omitempty"`
}
