/*
 * Nhss_imsSDM
 *
 * Nhss Subscriber Data Management Service for IMS.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.1.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package Nhss_imsSDM

type DataSetNameAnyOf string

// List of DataSetNameAnyOf
const (
	CHARGING_DATA DataSetNameAnyOf = "CHARGING_DATA"
	IFC_DATA DataSetNameAnyOf = "IFC_DATA"
	TRACE_DATA DataSetNameAnyOf = "TRACE_DATA"
	PRIORITY_DATA DataSetNameAnyOf = "PRIORITY_DATA"
)
