/*
 * Nhss_imsSDM
 *
 * Nhss Subscriber Data Management Service for IMS.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.1.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package Nhss_imsSDM

type ImsVoiceOverPsSessionSupportAnyOf string

// List of ImsVoiceOverPsSessionSupportAnyOf
const (
	NOT_SUPPORTED ImsVoiceOverPsSessionSupportAnyOf = "IMS_VOICE_OVER_PS_NOT_SUPPORTED"
	SUPPORTED ImsVoiceOverPsSessionSupportAnyOf = "IMS_VOICE_OVER_PS_SUPPORTED"
	SUPPORT_UNKNOWN ImsVoiceOverPsSessionSupportAnyOf = "IMS_VOICE_OVER_PS_SUPPORT_UNKNOWN"
)
