/*
 * Fault Supervision MnS
 *
 * OAS 3.0.1 definition of the Fault Supervision MnS © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 17.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package FaultMnS

type AlarmsAlarmIdPatchRequest struct {

	AckUserId string `json:"ackUserId"`

	AckSystemId string `json:"ackSystemId,omitempty"`

	AckState AckState `json:"ackState"`

	ClearUserId string `json:"clearUserId"`

	ClearSystemId string `json:"clearSystemId,omitempty"`

	PerceivedSeverity string `json:"perceivedSeverity"`
}
