/*
 * Ntsctsf_TimeSynchronization Service API
 *
 * TSCTSF Time Synchronization Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package Ntsctsf_TimeSynchronization

// TimeSyncCapability - Contains the capability of time synchronization service.
type TimeSyncCapability struct {

	// Integer where the allowed values correspond to the value range of an unsigned 64-bit integer. 
	UpNodeId int32 `json:"upNodeId"`

	GmCapables []GmCapable `json:"gmCapables,omitempty"`

	AsTimeRes AsTimeResource `json:"asTimeRes,omitempty"`

	// Contains the PTP capabilities supported by each of the SUPI(s). The key of the map is the SUPI. 
	PtpCapForUes map[string]PtpCapabilitiesPerUe `json:"ptpCapForUes,omitempty"`

	// Contains the PTP capabilities supported by each of the GPSI(s). The key of the map is the GPSI. 
	PtpCapForGpsis map[string]PtpCapabilitiesPerUe `json:"ptpCapForGpsis,omitempty"`
}
