/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package Nsmf_PDUSession

import (
	"os"
)

type ReleasePduSession200Response struct {

	JsonData ReleasedData `json:"jsonData,omitempty"`

	BinaryDataN4Information *os.File `json:"binaryDataN4Information,omitempty"`

	BinaryDataN4InformationExt1 *os.File `json:"binaryDataN4InformationExt1,omitempty"`

	BinaryDataN4InformationExt2 *os.File `json:"binaryDataN4InformationExt2,omitempty"`
}
