/*
 * Npcf_MBSPolicyControl API
 *
 * MBS Policy Control Service   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package Npcf_MBSPolicyControl

// AcceptableMbsServInfo - Contains the MBS Service Information that can be accepted by the PCF. 
type AcceptableMbsServInfo struct {

	AccMbsServInfo map[string]MbsMediaComp `json:"accMbsServInfo,omitempty"`

	// String representing a bit rate; the prefixes follow the standard symbols from The International System of Units, and represent x1000 multipliers, with the exception that prefix \"K\" is used to represent the standard symbol \"k\". 
	AccMaxMbsBw string `json:"accMaxMbsBw,omitempty"`
}
