/*
 * Npcf_MBSPolicyControl API
 *
 * MBS Policy Control Service   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package Npcf_MBSPolicyControl

// MbsReport - Contains information about the MBS Policy Decision level failure(s) and/or the MBS PCC rule level failure(s). 
type MbsReport struct {

	MbsPccRuleIds []string `json:"mbsPccRuleIds,omitempty"`

	MbsPccRuleStatus MbsPccRuleStatus `json:"mbsPccRuleStatus,omitempty"`

	FailureCode MbsFailureCode `json:"failureCode,omitempty"`
}
