/*
 * M1_EdgeResourcesProvisioning
 *
 * 5GMS AF M1 Edge Resources Provisioning API © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 2.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package M1_EdgeResourcesProvisioning

type EdgeManagementModeAnyOf string

// List of EdgeManagementModeAnyOf
const (
	AF_DRIVEN EdgeManagementModeAnyOf = "EM_AF_DRIVEN"
	APP_DRIVEN EdgeManagementModeAnyOf = "EM_APP_DRIVEN"
)
