/*
 * Ndcaf_DataReportingProvisioning
 *
 * Data Collection AF: Provisioning Sessions API © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package Ndcaf_DataReportingProvisioning

type DataAggregationFunctionTypeAnyOf string

// List of DataAggregationFunctionTypeAnyOf
const (
	NULL DataAggregationFunctionTypeAnyOf = "NULL"
	COUNT DataAggregationFunctionTypeAnyOf = "COUNT"
	MEAN DataAggregationFunctionTypeAnyOf = "MEAN"
	MAXIMUM DataAggregationFunctionTypeAnyOf = "MAXIMUM"
	MINIMUM DataAggregationFunctionTypeAnyOf = "MINIMUM"
	SUM DataAggregationFunctionTypeAnyOf = "SUM"
)
