/*
 * Nhss_imsUECM
 *
 * Nhss UE Context Management Service for IMS.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package Nhss_imsUECM

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// Authorize - Authorize IMS Identities to register in the network or establish multimedia sessions and return CSCF location if it is stored 
func Authorize(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
