/*
 * Nhss_imsUECM
 *
 * Nhss UE Context Management Service for IMS.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package Nhss_imsUECM

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// DeleteScscfRestorationInfo - Delete the S-CSCF restoration information of the UE
func DeleteScscfRestorationInfo(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetScscfRestorationInfo - Retrieve the S-CSCF restoration information of the UE
func GetScscfRestorationInfo(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UpdateScscfRestorationInfo - Update the S-CSCF restoration information of the UE
func UpdateScscfRestorationInfo(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
