/*
 * GBA BSF Nbsp_GBA Service
 *
 * GBA BSF Nbsp_GBA Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package Nbsp_GBA

type UeIdTypeAnyOf string

// List of UeIdTypeAnyOf
const (
	PUBLIC UeIdTypeAnyOf = "PUBLIC"
	PRIVATE UeIdTypeAnyOf = "PRIVATE"
)
