/*
 * 3GPP 5GC NRM
 *
 * OAS 3.0.1 specification of the 5GC NRM © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.
 *
 * API version: 17.7.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_5GcNrm

import (
	"time"
)

// ConditionData - Contains conditions of applicability for a rule.
type ConditionData struct {

	// Uniquely identifies the condition data within a PDU session.
	CondId string `json:"condId"`

	// string with format 'date-time' as defined in OpenAPI with 'nullable:true' property.  
	ActivationTime *time.Time `json:"activationTime,omitempty"`

	// string with format 'date-time' as defined in OpenAPI with 'nullable:true' property.  
	DeactivationTime *time.Time `json:"deactivationTime,omitempty"`

	AccessType AccessType `json:"accessType,omitempty"`

	RatType RatType `json:"ratType,omitempty"`
}
